//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class FrappeBackendClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Get Item list
     * @param fields (optional) 
     * @param filters (optional) 
     * @param order_by (optional) 
     * @param limit_start (optional) 
     * @param limit_page_length (optional) 
     * @return Successful response
     */
    item(fields: string | undefined, filters: string | undefined, order_by: string | undefined, limit_start: number | undefined, limit_page_length: number | undefined): Promise<Anonymous> {
        let url_ = this.baseUrl + "/api/resource/item?";
        if (fields === null)
            throw new Error("The parameter 'fields' cannot be null.");
        else if (fields !== undefined)
            url_ += "fields=" + encodeURIComponent("" + fields) + "&";
        if (filters === null)
            throw new Error("The parameter 'filters' cannot be null.");
        else if (filters !== undefined)
            url_ += "filters=" + encodeURIComponent("" + filters) + "&";
        if (order_by === null)
            throw new Error("The parameter 'order_by' cannot be null.");
        else if (order_by !== undefined)
            url_ += "order_by=" + encodeURIComponent("" + order_by) + "&";
        if (limit_start === null)
            throw new Error("The parameter 'limit_start' cannot be null.");
        else if (limit_start !== undefined)
            url_ += "limit_start=" + encodeURIComponent("" + limit_start) + "&";
        if (limit_page_length === null)
            throw new Error("The parameter 'limit_page_length' cannot be null.");
        else if (limit_page_length !== undefined)
            url_ += "limit_page_length=" + encodeURIComponent("" + limit_page_length) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processItem(_response);
        });
    }

    protected processItem(response: Response): Promise<Anonymous> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Anonymous.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Anonymous>(null as any);
    }
}

export class Item implements IItem {
    /** Details */
    details?: string;
    /** Series */
    naming_series?: string;
    /** Item Code */
    item_code!: string;
    /** Item Name */
    item_name?: string;
    /** Item Group */
    item_group!: string;
    /** Default Unit of Measure */
    stock_uom!: string;
    /** column_break0 */
    column_break0?: string;
    /** Disabled */
    disabled?: boolean;
    /** Allow Alternative Item */
    allow_alternative_item?: boolean;
    /** Maintain Stock */
    is_stock_item?: boolean;
    /** Has Variants */
    has_variants?: boolean;
    /** Opening Stock */
    opening_stock?: number;
    /** Valuation Rate */
    valuation_rate?: number;
    /** Standard Selling Rate */
    standard_rate?: number;
    /** Is Fixed Asset */
    is_fixed_asset?: boolean;
    /** Auto Create Assets on Purchase */
    auto_create_assets?: boolean;
    /** Create Grouped Asset */
    is_grouped_asset?: boolean;
    /** Asset Category */
    asset_category?: string;
    /** Asset Naming Series */
    asset_naming_series?: string;
    /** Over Delivery/Receipt Allowance (%) */
    over_delivery_receipt_allowance?: number;
    /** Over Billing Allowance (%) */
    over_billing_allowance?: number;
    /** Image */
    image?: string;
    /** Description */
    section_break_11?: string;
    /** Description */
    description?: string;
    /** Brand */
    brand?: string;
    /** Units of Measure */
    unit_of_measure_conversion?: string;
    /** UOMs */
    uoms?: string;
    /** Dashboard */
    dashboard_tab?: string;
    /** Inventory */
    inventory_section?: string;
    /** Inventory Settings */
    inventory_settings_section?: string;
    /** Shelf Life In Days */
    shelf_life_in_days?: number;
    /** End of Life */
    end_of_life?: Date;
    /** Default Material Request Type */
    default_material_request_type?: string;
    /** Valuation Method */
    valuation_method?: string;
    /** column_break1 */
    column_break1?: string;
    /** Warranty Period (in days) */
    warranty_period?: string;
    /** Weight Per Unit */
    weight_per_unit?: number;
    /** Weight UOM */
    weight_uom?: string;
    /** Allow Negative Stock */
    allow_negative_stock?: boolean;
    /** Barcodes */
    sb_barcodes?: string;
    /** Barcodes */
    barcodes?: string;
    /** Auto re-order */
    reorder_section?: string;
    /** Reorder level based on Warehouse */
    reorder_levels?: string;
    /** Serial Nos and Batches */
    serial_nos_and_batches?: string;
    /** Has Batch No */
    has_batch_no?: boolean;
    /** Automatically Create New Batch */
    create_new_batch?: boolean;
    /** Batch Number Series */
    batch_number_series?: string;
    /** Has Expiry Date */
    has_expiry_date?: boolean;
    /** Retain Sample */
    retain_sample?: boolean;
    /** Max Sample Quantity */
    sample_quantity?: number;
    /** column_break_37 */
    column_break_37?: string;
    /** Has Serial No */
    has_serial_no?: boolean;
    /** Serial Number Series */
    serial_no_series?: string;
    /** Variants */
    variants_section?: string;
    /** Variant Of */
    variant_of?: string;
    /** Variant Based On */
    variant_based_on?: string;
    /** Variant Attributes */
    attributes?: string;
    /** Accounting */
    accounting?: string;
    /** Deferred Accounting */
    deferred_accounting_section?: string;
    /** Enable Deferred Expense */
    enable_deferred_expense?: boolean;
    /** No of Months (Expense) */
    no_of_months_exp?: number;
    /** column_break_9s9o */
    column_break_9s9o?: string;
    /** Enable Deferred Revenue */
    enable_deferred_revenue?: boolean;
    /** No of Months (Revenue) */
    no_of_months?: number;
    /** section_break_avcp */
    section_break_avcp?: string;
    /** Item Defaults */
    item_defaults?: string;
    /** Purchasing */
    purchasing_tab?: string;
    /** Default Purchase Unit of Measure */
    purchase_uom?: string;
    /** Minimum Order Qty */
    min_order_qty?: number;
    /** Safety Stock */
    safety_stock?: number;
    /** Allow Purchase */
    is_purchase_item?: boolean;
    /** purchase_details_cb */
    purchase_details_cb?: string;
    /** Lead Time in days */
    lead_time_days?: number;
    /** Last Purchase Rate */
    last_purchase_rate?: number;
    /** Is Customer Provided Item */
    is_customer_provided_item?: boolean;
    /** Customer */
    customer?: string;
    /** Supplier Details */
    supplier_details?: string;
    /** Delivered by Supplier (Drop Ship) */
    delivered_by_supplier?: boolean;
    /** column_break2 */
    column_break2?: string;
    /** Supplier Items */
    supplier_items?: string;
    /** Foreign Trade Details */
    foreign_trade_details?: string;
    /** Country of Origin */
    country_of_origin?: string;
    /** column_break_59 */
    column_break_59?: string;
    /** Customs Tariff Number */
    customs_tariff_number?: string;
    /** Sales */
    sales_details?: string;
    /** Default Sales Unit of Measure */
    sales_uom?: string;
    /** Grant Commission */
    grant_commission?: boolean;
    /** Allow Sales */
    is_sales_item?: boolean;
    /** column_break3 */
    column_break3?: string;
    /** Max Discount (%) */
    max_discount?: number;
    /** Customer Details */
    customer_details?: string;
    /** Customer Items */
    customer_items?: string;
    /** Tax */
    item_tax_section_break?: string;
    /** Taxes */
    taxes?: string;
    /** Quality */
    quality_tab?: string;
    /** Inspection Required before Purchase */
    inspection_required_before_purchase?: boolean;
    /** Quality Inspection Template */
    quality_inspection_template?: string;
    /** Inspection Required before Delivery */
    inspection_required_before_delivery?: boolean;
    /** Manufacturing */
    manufacturing?: string;
    /** Include Item In Manufacturing */
    include_item_in_manufacturing?: boolean;
    /** Supply Raw Materials for Purchase */
    is_sub_contracted_item?: boolean;
    /** Default BOM */
    default_bom?: string;
    /** column_break_74 */
    column_break_74?: string;
    /** Customer Code */
    customer_code?: string;
    /** Default Item Manufacturer */
    default_item_manufacturer?: string;
    /** Default Manufacturer Part No */
    default_manufacturer_part_no?: string;
    /** Total Projected Qty */
    total_projected_qty?: number;

    [key: string]: any;

    constructor(data?: IItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.details = _data["details"];
            this.naming_series = _data["naming_series"];
            this.item_code = _data["item_code"];
            this.item_name = _data["item_name"];
            this.item_group = _data["item_group"];
            this.stock_uom = _data["stock_uom"];
            this.column_break0 = _data["column_break0"];
            this.disabled = _data["disabled"];
            this.allow_alternative_item = _data["allow_alternative_item"];
            this.is_stock_item = _data["is_stock_item"];
            this.has_variants = _data["has_variants"];
            this.opening_stock = _data["opening_stock"];
            this.valuation_rate = _data["valuation_rate"];
            this.standard_rate = _data["standard_rate"];
            this.is_fixed_asset = _data["is_fixed_asset"];
            this.auto_create_assets = _data["auto_create_assets"];
            this.is_grouped_asset = _data["is_grouped_asset"];
            this.asset_category = _data["asset_category"];
            this.asset_naming_series = _data["asset_naming_series"];
            this.over_delivery_receipt_allowance = _data["over_delivery_receipt_allowance"];
            this.over_billing_allowance = _data["over_billing_allowance"];
            this.image = _data["image"];
            this.section_break_11 = _data["section_break_11"];
            this.description = _data["description"];
            this.brand = _data["brand"];
            this.unit_of_measure_conversion = _data["unit_of_measure_conversion"];
            this.uoms = _data["uoms"];
            this.dashboard_tab = _data["dashboard_tab"];
            this.inventory_section = _data["inventory_section"];
            this.inventory_settings_section = _data["inventory_settings_section"];
            this.shelf_life_in_days = _data["shelf_life_in_days"];
            this.end_of_life = _data["end_of_life"] ? new Date(_data["end_of_life"].toString()) : <any>undefined;
            this.default_material_request_type = _data["default_material_request_type"];
            this.valuation_method = _data["valuation_method"];
            this.column_break1 = _data["column_break1"];
            this.warranty_period = _data["warranty_period"];
            this.weight_per_unit = _data["weight_per_unit"];
            this.weight_uom = _data["weight_uom"];
            this.allow_negative_stock = _data["allow_negative_stock"];
            this.sb_barcodes = _data["sb_barcodes"];
            this.barcodes = _data["barcodes"];
            this.reorder_section = _data["reorder_section"];
            this.reorder_levels = _data["reorder_levels"];
            this.serial_nos_and_batches = _data["serial_nos_and_batches"];
            this.has_batch_no = _data["has_batch_no"];
            this.create_new_batch = _data["create_new_batch"];
            this.batch_number_series = _data["batch_number_series"];
            this.has_expiry_date = _data["has_expiry_date"];
            this.retain_sample = _data["retain_sample"];
            this.sample_quantity = _data["sample_quantity"];
            this.column_break_37 = _data["column_break_37"];
            this.has_serial_no = _data["has_serial_no"];
            this.serial_no_series = _data["serial_no_series"];
            this.variants_section = _data["variants_section"];
            this.variant_of = _data["variant_of"];
            this.variant_based_on = _data["variant_based_on"];
            this.attributes = _data["attributes"];
            this.accounting = _data["accounting"];
            this.deferred_accounting_section = _data["deferred_accounting_section"];
            this.enable_deferred_expense = _data["enable_deferred_expense"];
            this.no_of_months_exp = _data["no_of_months_exp"];
            this.column_break_9s9o = _data["column_break_9s9o"];
            this.enable_deferred_revenue = _data["enable_deferred_revenue"];
            this.no_of_months = _data["no_of_months"];
            this.section_break_avcp = _data["section_break_avcp"];
            this.item_defaults = _data["item_defaults"];
            this.purchasing_tab = _data["purchasing_tab"];
            this.purchase_uom = _data["purchase_uom"];
            this.min_order_qty = _data["min_order_qty"];
            this.safety_stock = _data["safety_stock"];
            this.is_purchase_item = _data["is_purchase_item"];
            this.purchase_details_cb = _data["purchase_details_cb"];
            this.lead_time_days = _data["lead_time_days"];
            this.last_purchase_rate = _data["last_purchase_rate"];
            this.is_customer_provided_item = _data["is_customer_provided_item"];
            this.customer = _data["customer"];
            this.supplier_details = _data["supplier_details"];
            this.delivered_by_supplier = _data["delivered_by_supplier"];
            this.column_break2 = _data["column_break2"];
            this.supplier_items = _data["supplier_items"];
            this.foreign_trade_details = _data["foreign_trade_details"];
            this.country_of_origin = _data["country_of_origin"];
            this.column_break_59 = _data["column_break_59"];
            this.customs_tariff_number = _data["customs_tariff_number"];
            this.sales_details = _data["sales_details"];
            this.sales_uom = _data["sales_uom"];
            this.grant_commission = _data["grant_commission"];
            this.is_sales_item = _data["is_sales_item"];
            this.column_break3 = _data["column_break3"];
            this.max_discount = _data["max_discount"];
            this.customer_details = _data["customer_details"];
            this.customer_items = _data["customer_items"];
            this.item_tax_section_break = _data["item_tax_section_break"];
            this.taxes = _data["taxes"];
            this.quality_tab = _data["quality_tab"];
            this.inspection_required_before_purchase = _data["inspection_required_before_purchase"];
            this.quality_inspection_template = _data["quality_inspection_template"];
            this.inspection_required_before_delivery = _data["inspection_required_before_delivery"];
            this.manufacturing = _data["manufacturing"];
            this.include_item_in_manufacturing = _data["include_item_in_manufacturing"];
            this.is_sub_contracted_item = _data["is_sub_contracted_item"];
            this.default_bom = _data["default_bom"];
            this.column_break_74 = _data["column_break_74"];
            this.customer_code = _data["customer_code"];
            this.default_item_manufacturer = _data["default_item_manufacturer"];
            this.default_manufacturer_part_no = _data["default_manufacturer_part_no"];
            this.total_projected_qty = _data["total_projected_qty"];
        }
    }

    static fromJS(data: any): Item {
        data = typeof data === 'object' ? data : {};
        let result = new Item();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["details"] = this.details;
        data["naming_series"] = this.naming_series;
        data["item_code"] = this.item_code;
        data["item_name"] = this.item_name;
        data["item_group"] = this.item_group;
        data["stock_uom"] = this.stock_uom;
        data["column_break0"] = this.column_break0;
        data["disabled"] = this.disabled;
        data["allow_alternative_item"] = this.allow_alternative_item;
        data["is_stock_item"] = this.is_stock_item;
        data["has_variants"] = this.has_variants;
        data["opening_stock"] = this.opening_stock;
        data["valuation_rate"] = this.valuation_rate;
        data["standard_rate"] = this.standard_rate;
        data["is_fixed_asset"] = this.is_fixed_asset;
        data["auto_create_assets"] = this.auto_create_assets;
        data["is_grouped_asset"] = this.is_grouped_asset;
        data["asset_category"] = this.asset_category;
        data["asset_naming_series"] = this.asset_naming_series;
        data["over_delivery_receipt_allowance"] = this.over_delivery_receipt_allowance;
        data["over_billing_allowance"] = this.over_billing_allowance;
        data["image"] = this.image;
        data["section_break_11"] = this.section_break_11;
        data["description"] = this.description;
        data["brand"] = this.brand;
        data["unit_of_measure_conversion"] = this.unit_of_measure_conversion;
        data["uoms"] = this.uoms;
        data["dashboard_tab"] = this.dashboard_tab;
        data["inventory_section"] = this.inventory_section;
        data["inventory_settings_section"] = this.inventory_settings_section;
        data["shelf_life_in_days"] = this.shelf_life_in_days;
        data["end_of_life"] = this.end_of_life ? this.end_of_life.toISOString() : <any>undefined;
        data["default_material_request_type"] = this.default_material_request_type;
        data["valuation_method"] = this.valuation_method;
        data["column_break1"] = this.column_break1;
        data["warranty_period"] = this.warranty_period;
        data["weight_per_unit"] = this.weight_per_unit;
        data["weight_uom"] = this.weight_uom;
        data["allow_negative_stock"] = this.allow_negative_stock;
        data["sb_barcodes"] = this.sb_barcodes;
        data["barcodes"] = this.barcodes;
        data["reorder_section"] = this.reorder_section;
        data["reorder_levels"] = this.reorder_levels;
        data["serial_nos_and_batches"] = this.serial_nos_and_batches;
        data["has_batch_no"] = this.has_batch_no;
        data["create_new_batch"] = this.create_new_batch;
        data["batch_number_series"] = this.batch_number_series;
        data["has_expiry_date"] = this.has_expiry_date;
        data["retain_sample"] = this.retain_sample;
        data["sample_quantity"] = this.sample_quantity;
        data["column_break_37"] = this.column_break_37;
        data["has_serial_no"] = this.has_serial_no;
        data["serial_no_series"] = this.serial_no_series;
        data["variants_section"] = this.variants_section;
        data["variant_of"] = this.variant_of;
        data["variant_based_on"] = this.variant_based_on;
        data["attributes"] = this.attributes;
        data["accounting"] = this.accounting;
        data["deferred_accounting_section"] = this.deferred_accounting_section;
        data["enable_deferred_expense"] = this.enable_deferred_expense;
        data["no_of_months_exp"] = this.no_of_months_exp;
        data["column_break_9s9o"] = this.column_break_9s9o;
        data["enable_deferred_revenue"] = this.enable_deferred_revenue;
        data["no_of_months"] = this.no_of_months;
        data["section_break_avcp"] = this.section_break_avcp;
        data["item_defaults"] = this.item_defaults;
        data["purchasing_tab"] = this.purchasing_tab;
        data["purchase_uom"] = this.purchase_uom;
        data["min_order_qty"] = this.min_order_qty;
        data["safety_stock"] = this.safety_stock;
        data["is_purchase_item"] = this.is_purchase_item;
        data["purchase_details_cb"] = this.purchase_details_cb;
        data["lead_time_days"] = this.lead_time_days;
        data["last_purchase_rate"] = this.last_purchase_rate;
        data["is_customer_provided_item"] = this.is_customer_provided_item;
        data["customer"] = this.customer;
        data["supplier_details"] = this.supplier_details;
        data["delivered_by_supplier"] = this.delivered_by_supplier;
        data["column_break2"] = this.column_break2;
        data["supplier_items"] = this.supplier_items;
        data["foreign_trade_details"] = this.foreign_trade_details;
        data["country_of_origin"] = this.country_of_origin;
        data["column_break_59"] = this.column_break_59;
        data["customs_tariff_number"] = this.customs_tariff_number;
        data["sales_details"] = this.sales_details;
        data["sales_uom"] = this.sales_uom;
        data["grant_commission"] = this.grant_commission;
        data["is_sales_item"] = this.is_sales_item;
        data["column_break3"] = this.column_break3;
        data["max_discount"] = this.max_discount;
        data["customer_details"] = this.customer_details;
        data["customer_items"] = this.customer_items;
        data["item_tax_section_break"] = this.item_tax_section_break;
        data["taxes"] = this.taxes;
        data["quality_tab"] = this.quality_tab;
        data["inspection_required_before_purchase"] = this.inspection_required_before_purchase;
        data["quality_inspection_template"] = this.quality_inspection_template;
        data["inspection_required_before_delivery"] = this.inspection_required_before_delivery;
        data["manufacturing"] = this.manufacturing;
        data["include_item_in_manufacturing"] = this.include_item_in_manufacturing;
        data["is_sub_contracted_item"] = this.is_sub_contracted_item;
        data["default_bom"] = this.default_bom;
        data["column_break_74"] = this.column_break_74;
        data["customer_code"] = this.customer_code;
        data["default_item_manufacturer"] = this.default_item_manufacturer;
        data["default_manufacturer_part_no"] = this.default_manufacturer_part_no;
        data["total_projected_qty"] = this.total_projected_qty;
        return data;
    }
}

export interface IItem {
    /** Details */
    details?: string;
    /** Series */
    naming_series?: string;
    /** Item Code */
    item_code: string;
    /** Item Name */
    item_name?: string;
    /** Item Group */
    item_group: string;
    /** Default Unit of Measure */
    stock_uom: string;
    /** column_break0 */
    column_break0?: string;
    /** Disabled */
    disabled?: boolean;
    /** Allow Alternative Item */
    allow_alternative_item?: boolean;
    /** Maintain Stock */
    is_stock_item?: boolean;
    /** Has Variants */
    has_variants?: boolean;
    /** Opening Stock */
    opening_stock?: number;
    /** Valuation Rate */
    valuation_rate?: number;
    /** Standard Selling Rate */
    standard_rate?: number;
    /** Is Fixed Asset */
    is_fixed_asset?: boolean;
    /** Auto Create Assets on Purchase */
    auto_create_assets?: boolean;
    /** Create Grouped Asset */
    is_grouped_asset?: boolean;
    /** Asset Category */
    asset_category?: string;
    /** Asset Naming Series */
    asset_naming_series?: string;
    /** Over Delivery/Receipt Allowance (%) */
    over_delivery_receipt_allowance?: number;
    /** Over Billing Allowance (%) */
    over_billing_allowance?: number;
    /** Image */
    image?: string;
    /** Description */
    section_break_11?: string;
    /** Description */
    description?: string;
    /** Brand */
    brand?: string;
    /** Units of Measure */
    unit_of_measure_conversion?: string;
    /** UOMs */
    uoms?: string;
    /** Dashboard */
    dashboard_tab?: string;
    /** Inventory */
    inventory_section?: string;
    /** Inventory Settings */
    inventory_settings_section?: string;
    /** Shelf Life In Days */
    shelf_life_in_days?: number;
    /** End of Life */
    end_of_life?: Date;
    /** Default Material Request Type */
    default_material_request_type?: string;
    /** Valuation Method */
    valuation_method?: string;
    /** column_break1 */
    column_break1?: string;
    /** Warranty Period (in days) */
    warranty_period?: string;
    /** Weight Per Unit */
    weight_per_unit?: number;
    /** Weight UOM */
    weight_uom?: string;
    /** Allow Negative Stock */
    allow_negative_stock?: boolean;
    /** Barcodes */
    sb_barcodes?: string;
    /** Barcodes */
    barcodes?: string;
    /** Auto re-order */
    reorder_section?: string;
    /** Reorder level based on Warehouse */
    reorder_levels?: string;
    /** Serial Nos and Batches */
    serial_nos_and_batches?: string;
    /** Has Batch No */
    has_batch_no?: boolean;
    /** Automatically Create New Batch */
    create_new_batch?: boolean;
    /** Batch Number Series */
    batch_number_series?: string;
    /** Has Expiry Date */
    has_expiry_date?: boolean;
    /** Retain Sample */
    retain_sample?: boolean;
    /** Max Sample Quantity */
    sample_quantity?: number;
    /** column_break_37 */
    column_break_37?: string;
    /** Has Serial No */
    has_serial_no?: boolean;
    /** Serial Number Series */
    serial_no_series?: string;
    /** Variants */
    variants_section?: string;
    /** Variant Of */
    variant_of?: string;
    /** Variant Based On */
    variant_based_on?: string;
    /** Variant Attributes */
    attributes?: string;
    /** Accounting */
    accounting?: string;
    /** Deferred Accounting */
    deferred_accounting_section?: string;
    /** Enable Deferred Expense */
    enable_deferred_expense?: boolean;
    /** No of Months (Expense) */
    no_of_months_exp?: number;
    /** column_break_9s9o */
    column_break_9s9o?: string;
    /** Enable Deferred Revenue */
    enable_deferred_revenue?: boolean;
    /** No of Months (Revenue) */
    no_of_months?: number;
    /** section_break_avcp */
    section_break_avcp?: string;
    /** Item Defaults */
    item_defaults?: string;
    /** Purchasing */
    purchasing_tab?: string;
    /** Default Purchase Unit of Measure */
    purchase_uom?: string;
    /** Minimum Order Qty */
    min_order_qty?: number;
    /** Safety Stock */
    safety_stock?: number;
    /** Allow Purchase */
    is_purchase_item?: boolean;
    /** purchase_details_cb */
    purchase_details_cb?: string;
    /** Lead Time in days */
    lead_time_days?: number;
    /** Last Purchase Rate */
    last_purchase_rate?: number;
    /** Is Customer Provided Item */
    is_customer_provided_item?: boolean;
    /** Customer */
    customer?: string;
    /** Supplier Details */
    supplier_details?: string;
    /** Delivered by Supplier (Drop Ship) */
    delivered_by_supplier?: boolean;
    /** column_break2 */
    column_break2?: string;
    /** Supplier Items */
    supplier_items?: string;
    /** Foreign Trade Details */
    foreign_trade_details?: string;
    /** Country of Origin */
    country_of_origin?: string;
    /** column_break_59 */
    column_break_59?: string;
    /** Customs Tariff Number */
    customs_tariff_number?: string;
    /** Sales */
    sales_details?: string;
    /** Default Sales Unit of Measure */
    sales_uom?: string;
    /** Grant Commission */
    grant_commission?: boolean;
    /** Allow Sales */
    is_sales_item?: boolean;
    /** column_break3 */
    column_break3?: string;
    /** Max Discount (%) */
    max_discount?: number;
    /** Customer Details */
    customer_details?: string;
    /** Customer Items */
    customer_items?: string;
    /** Tax */
    item_tax_section_break?: string;
    /** Taxes */
    taxes?: string;
    /** Quality */
    quality_tab?: string;
    /** Inspection Required before Purchase */
    inspection_required_before_purchase?: boolean;
    /** Quality Inspection Template */
    quality_inspection_template?: string;
    /** Inspection Required before Delivery */
    inspection_required_before_delivery?: boolean;
    /** Manufacturing */
    manufacturing?: string;
    /** Include Item In Manufacturing */
    include_item_in_manufacturing?: boolean;
    /** Supply Raw Materials for Purchase */
    is_sub_contracted_item?: boolean;
    /** Default BOM */
    default_bom?: string;
    /** column_break_74 */
    column_break_74?: string;
    /** Customer Code */
    customer_code?: string;
    /** Default Item Manufacturer */
    default_item_manufacturer?: string;
    /** Default Manufacturer Part No */
    default_manufacturer_part_no?: string;
    /** Total Projected Qty */
    total_projected_qty?: number;

    [key: string]: any;
}

export class Anonymous implements IAnonymous {
    data?: Item[];

    [key: string]: any;

    constructor(data?: IAnonymous) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["data"])) {
                this.data = [] as any;
                for (let item of _data["data"])
                    this.data!.push(Item.fromJS(item));
            }
        }
    }

    static fromJS(data: any): Anonymous {
        data = typeof data === 'object' ? data : {};
        let result = new Anonymous();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.data)) {
            data["data"] = [];
            for (let item of this.data)
                data["data"].push(item.toJSON());
        }
        return data;
    }
}

export interface IAnonymous {
    data?: Item[];

    [key: string]: any;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}