version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Ebay"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/src/ChromeExtension"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "pip"
    directory: "/src/frappe_ebay"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"