version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Ebay"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/src/ChromeExtension"
    schedule:
      interval: "monthly"