swagger: '2.0'
info:
  description: EbayApi
  title: EbayApi
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
basePath: /api/ebay/v1/
paths:
  /:
    get:
      operationId: GetAll
      summary: List API versions
      responses:
        200:
          description: 'OK'
          schema:
            type: array
            items:
              $ref: '#/definitions/WeatherForecast'

definitions:
  WeatherForecast:
    type: object
    properties:
      Date:
        type: string
      TemperatureC:
        type: string
      Summary:
        type: string
      TemperatureF:
        type: string