swagger: '2.0'
info:
  description: EbayApi
  title: EbayApi
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
basePath: /api/ebay/v1/
paths:
  /products:
    get:
      operationId: GetAllProducts
      summary: List all products
      responses:
        200:
          description: 'OK'
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductWithId'
    post:
      operationId: CreateProduct
      summary: Create product
      parameters:
        - name: product
          in: body
          required: true
          schema:
            $ref: '#/definitions/ProductWithoutId'
      responses:
        200:
          description: 'Updated'
          schema:
            type: string
            format: guid
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/ValidationProblemDetails'
  
  /products/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: string
        format: guid
    put:
      operationId: UpdateProduct
      summary: Update product
      parameters:
        - name: product
          in: body
          required: true
          schema:
            $ref: '#/definitions/ProductWithoutId'
      responses:
        200:
          description: 'Updated'
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/ValidationProblemDetails'
    delete:
      operationId: DeleteProduct
      summary: Delete product
      responses:
        200:
          description: 'Deleted'


definitions:
  ProductWithoutId:
    type: object
    properties:
      Name:
        type: string
        pattern: ^\d+$
        minLength: 1
      SearchQuery:
        type: string
        pattern: ^\d+$
        minLength: 1
    required:
      - Name
      - SearchQuery
  
  ProductWithId:
    type: object
    properties:
      Id:
        type: string
        format: guid
        minLength: 1
      Name:
        type: string
        minLength: 1
      SearchQuery:
        type: string
        minLength: 1
    required:
      - Id
      - Name
      - SearchQuery

  ProblemDetails:
    x-abstract: true
    properties:
      type:
        type: string
      title:
        type: string
      status:
        type: integer
      detail:
        type: string
      instance:
        type: string
  
  ValidationProblemDetails:
    allOf:
      - $ref: '#/definitions/ProblemDetails'
    properties:
      errors:
        additionalProperties: { }