swagger: '2.0'
info:
  description: EbayApi
  title: EbayApi
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
basePath: /api/ebay/v1
paths:
  /products:
    get:
      operationId: GetAllProducts
      summary: List all products
      responses:
        200:
          description: 'OK'
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductWithId'
    post:
      operationId: CreateProduct
      summary: Create product
      parameters:
        - name: product
          in: body
          required: true
          schema:
            $ref: '#/definitions/ProductWithoutId'
      responses:
        200:
          description: 'Updated'
          schema:
            type: string
            format: guid
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/ValidationProblemDetailedInfo'
  
  /products/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: string
        format: guid
    put:
      operationId: UpdateProduct
      summary: Update product
      parameters:
        - name: product
          in: body
          required: true
          schema:
            $ref: '#/definitions/ProductWithoutId'
      responses:
        200:
          description: 'Updated'
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/ValidationProblemDetailedInfo'
    get:
      operationId: GetProduct
      responses: 
        200:
          description: Ok
          schema:
            $ref: '#/definitions/ProductWithId'
        400:
          description: 'Error'
          schema:
            $ref: '#/definitions/NotFoundProblemDetailedInfo' 
    delete:
      operationId: DeleteProduct
      summary: Delete product
      responses:
        200:
          description: 'Deleted'
  
  /products/{id}/mark_as_checked/:
    parameters:
      - name: id
        in: path
        required: true
        type: string
        format: guid
    post:
      operationId: MarkProductAsChecked
      summary: MarkProductAsChecked
      responses:
        200:
          description: 'Updated'
        400:
          description: 'NotFound'
          schema:
            $ref: '#/definitions/NotFoundProblemDetailedInfo'

  /products/{productId}/lots/:
    parameters:
      - name: productId
        in: path
        required: true
        type: string
        format: guid
    get:
      operationId: GetLots
      responses: 
        200:
          description: Ok
          schema:
            type: array
            items:
               $ref: '#/definitions/LotInfoWithProductId'
        400:
          description: 'NotFound'
          schema:
            $ref: '#/definitions/NotFoundProblemDetailedInfo'
    post:
      operationId: UpsertLotInfo
      summary: Обновляет информацию о лоте
      parameters:
        - name: lotInfo
          in: body
          required: true
          schema:
            $ref: '#/definitions/LotInfo'
      responses:
        200:
          description: 'Ok'
        400:
          description: 'NotFound'
          schema:
            $ref: '#/definitions/ValidationProblemDetailedInfo'

  /lots/{lotId}/:
    parameters:
      - name: lotId
        in: path
        required: true
        type: integer
        format: int64
    get:
      operationId: GetLotInfo
      summary: Получить информацию о лоте
      responses:
        200:
          description: 'Ok'
          schema:
            $ref: '#/definitions/LotInfoWithProductId'
        400:
          description: 'NotFound'
          schema:
            $ref: '#/definitions/NotFoundProblemDetailedInfo'
  
  
  /lot_state_requests/:
    post:
      operationId: GetLotStates
      summary: Получает информацию о учтенных лотах
      parameters:
        - name: lotIds
          in: body
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        200:
          description: 'Ok'
          schema:
            type: array
            items:
              $ref: '#/definitions/LotState'
  
  /manual_conditions/:
    get:
      operationId: GetManualConditionsList
      summary: Отдает перечень возможных состояний продаваемого товара
      responses:
        200:
          description: 'Ok'
          schema:
            type: array
            items:
              $ref: '#/definitions/ManualCondition'

  /shipping_rates/:
    get:
      operationId: GetShippingRates
      responses:
        200:
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/ShippingType'
            minLength: 1

  /currencies/:
    get:
      operationId: GetCurrencies
      responses:
        200:
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/Currency'
            minLength: 1


  /error/:
    post:
      operationId: SaveError
      summary: Save Error
      parameters:
        - name: error
          in: body
          required: true
          schema:
            $ref: '#/definitions/ClientErrorInfo'
      responses:
        200:
          description: 'Ok'

definitions:
  ProductWithoutId:
    type: object
    properties:
      Name:
        type: string
        pattern: ^\w+(?:[ -]+\w+)*$
        minLength: 1
      SearchQueries:
        type: array
        items:
          $ref: '#/definitions/SearchQuery'
    required:
      - Name
      - SearchQueries
  
  ProductWithId:
    type: object
    properties:
      Id:
        type: string
        format: guid
        minLength: 1
      Name:
        type: string
        minLength: 1
      LastCheckTime:
        type: string
        pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$
        minLength: 1
      SearchQueries:
        type: array
        items:
          $ref: '#/definitions/SearchQuery'
    required:
      - Id
      - Name
      - SearchQueries
  
  SearchQuery:
    type: object
    properties:
      id:
        type: string
        format: guid
      query:
        type: string
        pattern: ^\w+(?:[ -]+\w+)*$
        minLength: 1
    required:
      - id
      - query
  
  LotInfoWithProductId:
    type: object
    properties:
      productId:
        type: string
        format: guid
      lotInfo:
        $ref: '#/definitions/LotInfo'
    required:
      - productId
      - lotInfo
  
  LotInfo:
    type: object
    properties:
      lotId:
        type: integer
        format: int64
      name:
        type: string
        minLength: 1
      pcs:
        type: integer
        minimum: 1
      shippingCountry:
        type: string
        minLength: 1
      currency:
        type: string
        minLength: 1
      price:
        type: number
        minimum: 0.01
      shipping:
        type: number
        minimum: 0
      shippingAdditional:
        type: number
        minimum: 0
      description:
        type: string
        minLength: 1
      condition:
        type: string
        minLength: 1
      conditionDescription:
        type: string
        minLength: 1
      seller:
        type: string
        minLength: 1
      locatedIn:
        type: string
        minLength: 1
      ignoreThatLot:
        type: boolean
      manualConditionId:
        type: string
        minLength: 1
        pattern: ^[A-Za-z]+$
      purchaseHistory:
        type: array
        items:
          $ref: '#/definitions/PurchaseInfo'
    required:
      - lotId
      - name
      - pcs
      - shippingCountry
      - currency
      - price
      - description
      - condition
      - seller
      - locatedIn
      - ignoreThatLot
      - manualConditionId
      - purchaseHistory

  PurchaseInfo:
    type: object
    properties:
      price:
        type: number
        minimum: 0.01
      quantity:
        type: integer
        minimum: 1
      date:
        type: string
        pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$
        minLength: 1
    required:
      - quantity
      - date
  
  ManualCondition:
    type: object
    properties:
      id:
        type: string
      description:
        type: string
    required:
      - id
      - description
  
  LotState:
    type: object
    properties:
      lotId:
        type: integer
        format: int64
      ignoreThatLot:
        type: boolean
      lastUpdate:
        type: string
        pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$
    required:
      - lotId
      - ignoreThatLot
      - lastUpdate

  ClientErrorInfo:
    type: object
    properties:
      url:
        type: string
      error:
        type: string
    required:
      - url
      - error

  ShippingType:
    type: object
    properties:
      name:
        type: string
        minLength: 1
      currency:
        type: string
        minLength: 1
      rates:
        type: array
        items:
          $ref: '#/definitions/ShippingRates'
        minLength: 1
    required:
      - name
      - rates
      - currency

  ShippingRates:
    type: object
    properties:
      specifiedCountries:
        type: array
        items:
          type: string
          minLength: 1
      rates:
        type: array
        items:
          $ref: '#/definitions/ShippingRate'
        minLength: 1
    required:
      - rates
  
  ShippingRate:
    type: object
    properties:
      minWeight:
        type: integer
        minimum: 0
      maxWeight:
        type: integer
        minimum: 0
      price:
        type: integer
        minimum: 0
    required:
      - minWeight
      - maxWeight

  Currency:
    type: object
    properties:
      ebayName:
        type: string
        minLength: 0
      rusName:
        type: string
        minLength: 0
      rate:
        type: number
        minimum: 0
      lastUpdate:
        type: string
        pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$
    required:
      - ebayName
      - rusName
      - rate
      - lastUpdate

      # далее ошибки
  ProblemDetailedInfo:
    x-abstract: true
    properties:
      type:
        type: string
      title:
        type: string
      status:
        type: integer
      detail:
        type: string
      instance:
        type: string
  
  NotFoundProblemDetailedInfo:
    allOf:
      - $ref: '#/definitions/ProblemDetailedInfo'
    properties:
      errors:
        additionalProperties: { }
  
  ValidationProblemDetailedInfo:
    allOf:
      - $ref: '#/definitions/ProblemDetailedInfo'
    properties:
      errors:
        additionalProperties: { }