swagger: '2.0'
info:
  description: EbayApi
  title: EbayApi
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
basePath: /api/ebay/v1/
paths:
  /products:
    get:
      operationId: GetAllProducts
      summary: List all products
      responses:
        200:
          description: 'OK'
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
    post:
      operationId: CreateProduct
      summary: Create product
      parameters:
        - name: product
          in: body
          required: true
          schema:
            $ref: '#/definitions/ProductWithoutId'
      responses:
        200:
          description: 'Created'
          schema:
            type: string
            format: guid
  
  /products/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: string
        format: guid
    put:
      operationId: UpdateProduct
      summary: Update product
      parameters:
        - name: product
          in: body
          required: true
          schema:
            $ref: '#/definitions/ProductWithoutId'
      responses: 
        200:
          description: 'Updated'
    delete:
      operationId: DeleteProduct
      summary: Delete product
      responses: 
        200:
          description: 'Deleted'
        

definitions:
  Product:
    type: object
    properties:
      Id:
        type: string
        format: guid
      Name:
        type: string
      SearchQuery:
        type: string
    required:
      - Id
      - Name
      - SearchQuery

  ProductWithoutId:
    type: object
    properties:
      Name:
        type: string
      SearchQuery:
        type: string
    required:
      - Name
      - SearchQuery