<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <RazorCompileOnBuild>true</RazorCompileOnBuild>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
  
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" />
    <PackageReference Include="Microsoft.AspNetCore.ApiAuthorization.IdentityServer" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="NSwag.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <AdditionalFiles Include="Areas\Identity\Pages\Shared\_LoginPartial.cshtml" />
    <AdditionalFiles Include="Pages\EbayLotDescriptionPage.cshtml" />
    <AdditionalFiles Include="Pages\Error.cshtml" />
    <AdditionalFiles Include="Pages\MeasurementPage.cshtml" />
    <AdditionalFiles Include="Pages\PurchasePage.cshtml" />
    <AdditionalFiles Include="Pages\Shared\_Metrics.cshtml" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Server.Application\Server.Application.csproj" />
    <ProjectReference Include="..\Server.Client\Server.Client.csproj" />
    <ProjectReference Include="..\Server.Domain\Server.Domain.csproj" />
  </ItemGroup>

  <Target Name="NSwag" BeforeTargets="BeforeBuild">
    <Exec Command="$(NSwagExe_Net100) openapi2cscontroller /input:Controllers/Contracts/Ebay.yaml /classname:Ebay /namespace:Server.Controllers.Generated /output:Controllers/Generated/EbayController.cs /ControllerBaseClass:Microsoft.AspNetCore.Mvc.Controller /UseCancellationToken:true /GenerateImmutableArrayProperties:true /GenerateImmutableDictionaryProperties:true /GenerateNullableReferenceTypes:true /GenerateOptionalPropertiesAsNullable:true /ClassStyle:Record /ExcludedTypeNames:ProblemDetails,ValidationProblemDetails /RequiredPropertiesMustBeDefined:false" />
    <Exec Command="$(NSwagExe_Net100) openapi2tsclient /input:Controllers/Contracts/Ebay.yaml /output:../../ChromeExtension/src/clients/Generated/EbayToolBackendClient.ts /ClassName:EbayToolBackendClient" />
  </Target>
</Project>
