version: "3"

services:
  ebay_postgres:
    container_name: ebay_postgres
    image: postgres:16.1
    ports:
      - "15432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ebay
      POSTGRES_PASSWORD: marine-4buckskin-drainage8
      POSTGRES_INITDB_ARGS: --locale='en_US.UTF8'
      CFG_TIMEZONE: 'Europe/Moscow'
    volumes:
      - pgdata:/var/lib/postgresql/data

  ebay_server:
    container_name: ebay_server
    image: ghcr.io/artyompetrov/ebay:latest
    ports:
      - "17443:5000"
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=https://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=qwerty123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/pfx.pfx
      - ASPNETCORE_IdentityServer__Key__Type=File
      - ASPNETCORE_IdentityServer__Key__FilePath=/https/pfx.pfx
      - ASPNETCORE_IdentityServer__Key__Password=qwerty123
      - ASPNETCORE_ConnectionStrings__DefaultConnection=User ID=ebay;Password=marine-4buckskin-drainage8;Server=postgres;Port=5432;Database=ebay;Pooling=true;MinPoolSize=1;MaxPoolSize=30;Enlist=true;
    volumes:
      - ./certs/pfx.pfx:/https/pfx.pfx:ro

volumes:
  pgdata: