version: "3"

services:
  ebay:
    container_name: ebay
    image: ghcr.io/artyompetrov/ebay:latest
    ports:
      - 17443:5000
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=https://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=qwerty123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/pfx.pfx
      - ASPNETCORE_IdentityServer__Key__Type=File
      - ASPNETCORE_IdentityServer__Key__FilePath=/https/pfx.pfx
      - ASPNETCORE_IdentityServer__Key__Password=qwerty123
    volumes:
      - ./certs/pfx.pfx:/https/pfx.pfx:ro