{
 "title": "Logging Dashboard via Loki",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service",
    "query": {}
   },
   {
    "name": "log_level",
    "label": "Log level",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Distribution of levels of \"$searchable_pattern\"",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=\"$service_name\", log_level=~\"$log_level\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (log_level)",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Total Count: of \"$searchable_pattern\"",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=~\"$service_name\", log_level=~\"$log_level\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Percentage for specified time of \"$searchable_pattern\" ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({service_name=\"$service_name\", log_level=~\"$log_level\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({service_name=\"$service_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{service_name=\"$service_name\", log_level=~\"$log_level\"} |~ \"(?i)$searchable_pattern\" | label_format level=log_level"
    }
   ]
  }
 ]
}