# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, constr

class ExtractorInfo(BaseModel):
    """
    ExtractorInfo
    """
    extracted_from: constr(strict=True, min_length=1) = Field(..., alias="extractedFrom")
    extractor: constr(strict=True, min_length=1) = Field(...)
    match: constr(strict=True, min_length=1) = Field(...)
    __properties = ["extractedFrom", "extractor", "match"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExtractorInfo:
        """Create an instance of ExtractorInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExtractorInfo:
        """Create an instance of ExtractorInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ExtractorInfo.parse_obj(obj)

        _obj = ExtractorInfo.parse_obj({
            "extracted_from": obj.get("extractedFrom"),
            "extractor": obj.get("extractor"),
            "match": obj.get("match")
        })
        return _obj


