# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictInt, confloat, conint, conlist, constr, validator
from openapi_client.models.purchase_info import PurchaseInfo

class LotInfoShort(BaseModel):
    """
    LotInfoShort
    """
    lot_id: StrictInt = Field(..., alias="lotId")
    name: constr(strict=True, min_length=1) = Field(...)
    pcs: conint(strict=True, ge=1) = Field(...)
    shipping_country: constr(strict=True, min_length=1) = Field(..., alias="shippingCountry")
    currency: constr(strict=True, min_length=1) = Field(...)
    price: Union[confloat(ge=0.01, strict=True), conint(ge=1, strict=True)] = Field(...)
    shipping: Optional[Union[confloat(ge=0, strict=True), conint(ge=0, strict=True)]] = None
    shipping_additional: Optional[Union[confloat(ge=0, strict=True), conint(ge=0, strict=True)]] = Field(None, alias="shippingAdditional")
    condition: constr(strict=True, min_length=1) = Field(...)
    condition_description: Optional[constr(strict=True, min_length=1)] = Field(None, alias="conditionDescription")
    seller: constr(strict=True, min_length=1) = Field(...)
    located_in: constr(strict=True, min_length=1) = Field(..., alias="locatedIn")
    manual_condition_id: constr(strict=True, min_length=1) = Field(..., alias="manualConditionId")
    title_change_date: constr(strict=True, min_length=1) = Field(..., alias="titleChangeDate")
    purchase_history: conlist(PurchaseInfo) = Field(..., alias="purchaseHistory")
    __properties = ["lotId", "name", "pcs", "shippingCountry", "currency", "price", "shipping", "shippingAdditional", "condition", "conditionDescription", "seller", "locatedIn", "manualConditionId", "titleChangeDate", "purchaseHistory"]

    @validator('manual_condition_id')
    def manual_condition_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Za-z]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z]+$/")
        return value

    @validator('title_change_date')
    def title_change_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LotInfoShort:
        """Create an instance of LotInfoShort from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in purchase_history (list)
        _items = []
        if self.purchase_history:
            for _item in self.purchase_history:
                if _item:
                    _items.append(_item.to_dict())
            _dict['purchaseHistory'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LotInfoShort:
        """Create an instance of LotInfoShort from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LotInfoShort.parse_obj(obj)

        _obj = LotInfoShort.parse_obj({
            "lot_id": obj.get("lotId"),
            "name": obj.get("name"),
            "pcs": obj.get("pcs"),
            "shipping_country": obj.get("shippingCountry"),
            "currency": obj.get("currency"),
            "price": obj.get("price"),
            "shipping": obj.get("shipping"),
            "shipping_additional": obj.get("shippingAdditional"),
            "condition": obj.get("condition"),
            "condition_description": obj.get("conditionDescription"),
            "seller": obj.get("seller"),
            "located_in": obj.get("locatedIn"),
            "manual_condition_id": obj.get("manualConditionId"),
            "title_change_date": obj.get("titleChangeDate"),
            "purchase_history": [PurchaseInfo.from_dict(_item) for _item in obj.get("purchaseHistory")] if obj.get("purchaseHistory") is not None else None
        })
        return _obj


