# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from openapi_client.models.lot_info import LotInfo

class LotInfoWithProductId(BaseModel):
    """
    LotInfoWithProductId
    """
    product_id: StrictStr = Field(..., alias="productId")
    lot_info: LotInfo = Field(..., alias="lotInfo")
    __properties = ["productId", "lotInfo"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LotInfoWithProductId:
        """Create an instance of LotInfoWithProductId from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of lot_info
        if self.lot_info:
            _dict['lotInfo'] = self.lot_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LotInfoWithProductId:
        """Create an instance of LotInfoWithProductId from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LotInfoWithProductId.parse_obj(obj)

        _obj = LotInfoWithProductId.parse_obj({
            "product_id": obj.get("productId"),
            "lot_info": LotInfo.from_dict(obj.get("lotInfo")) if obj.get("lotInfo") is not None else None
        })
        return _obj


