# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conint, conlist, constr, validator
from openapi_client.models.search_query import SearchQuery

class ProductWithoutId(BaseModel):
    """
    ProductWithoutId
    """
    name: constr(strict=True, min_length=1) = Field(..., alias="Name")
    search_queries: conlist(SearchQuery) = Field(..., alias="SearchQueries")
    weight: conint(strict=True, ge=5) = Field(..., alias="Weight")
    __properties = ["Name", "SearchQueries", "Weight"]

    @validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\w+(?:[ -\/\\.,]+\w+)*$", value):
            raise ValueError(r"must validate the regular expression /^\w+(?:[ -\/\\.,]+\w+)*$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProductWithoutId:
        """Create an instance of ProductWithoutId from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in search_queries (list)
        _items = []
        if self.search_queries:
            for _item in self.search_queries:
                if _item:
                    _items.append(_item.to_dict())
            _dict['SearchQueries'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProductWithoutId:
        """Create an instance of ProductWithoutId from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProductWithoutId.parse_obj(obj)

        _obj = ProductWithoutId.parse_obj({
            "name": obj.get("Name"),
            "search_queries": [SearchQuery.from_dict(_item) for _item in obj.get("SearchQueries")] if obj.get("SearchQueries") is not None else None,
            "weight": obj.get("Weight")
        })
        return _obj


