auth_enabled: false

server:
  http_listen_port: 3100

limits_config:
  allow_structured_metadata: true
  retention_period: 30d

# <<< общий ring через memberlist (заменяет consul)
common:
  path_prefix: /var/lib/loki
  ring:
    kvstore:
      store: memberlist

# memberlist без кластера
memberlist:
  join_members: []

# (не обязательно, но ок) ring именно для scheduler'а
query_scheduler:
  scheduler_ring:
    kvstore:
      store: memberlist

# выключаем usage analytics, чтобы модуль не тянул ring
analytics:
  reporting_enabled: false

# WAL в том же томе
ingester:
  wal:
    enabled: true
    dir: /var/lib/loki/wal

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /var/lib/loki/chunks
  tsdb_shipper:
    active_index_directory: /var/lib/loki/index
    cache_location: /var/lib/loki/tsdb-cache
    # cache_ttl: 24h

compactor:
  working_directory: /var/lib/loki/compactor
  retention_enabled: true
  delete_request_store: filesystem
