<Project Sdk="Microsoft.NET.Sdk">

  <!--
    Архитектурное правило (ports-and-adapters):
    - application-слой должен зависеть от доменного слоя (Server.Domain);
    - зависимости на внешние библиотеки допустимы только в порядке исключения,
      когда без них невозможно реализовать слой приложения.
  -->
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Models\\MeasurementInfo.fs" />
    <Compile Include="Models\\MeasurementInfoWithSimilarMeasurements.fs" />
    <Compile Include="Models\\MeasurementInfoWithData.fs" />
    <Compile Include="Models\\Passport.fs" />
    <Compile Include="Models\\ProductInfo.fs" />
    <Compile Include="Models\\TubeWorkingPointInfo.fs" />

    <Compile Include="Abstractions\\IRepository.fs" />
    <Compile Include="Abstractions\\IUnitOfWorkTransaction.fs" />
    <Compile Include="Abstractions\\IUnitOfWork.fs" />

    <Compile Include="Abstractions\\Queries\\IMeasurementQueries.fs" />
    <Compile Include="Abstractions\\Queries\\IPassportQueries.fs" />
    <Compile Include="Abstractions\\Queries\\IProductQueries.fs" />
    <Compile Include="Abstractions\\Queries\\ITubeWorkingPointQueries.fs" />

    <Compile Include="Abstractions\\Repositories\\IMeasurementRepository.fs" />
    <Compile Include="Abstractions\\Repositories\\IMatchedPairDifferenceRepository.fs" />
    <Compile Include="Abstractions\\Repositories\\IProductRepository.fs" />
    <Compile Include="Abstractions\\Repositories\\ITubeWorkingPointsRepository.fs" />

    <Compile Include="Abstractions\\Services\\IMeasurementService.fs" />

    <Compile Include="Services\\MeasurementService.fs" />
    <Compile Include="ServiceCollectionExtensions.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Server.Domain\\Server.Domain.csproj" />
  </ItemGroup>

</Project>
