LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule ssl_module modules/mod_ssl.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule headers_module modules/mod_headers.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_user_module modules/mod_authz_user.so

ServerName ${DOMAIN}
Listen 10000
Listen 10001
User www-data
Group www-data

SSLSessionCache shmcb:/usr/local/apache2/logs/ssl_scache(512000)

<VirtualHost *:10000>
    ProxyPreserveHost On

    # Redirect longpolling requests to Odoo longpolling port
    ProxyPass /longpolling http://ebay_odoo:8072/ retry=0
    ProxyPassReverse /longpolling http://ebay_odoo:8072/
    
    # Redirect other requests to Odoo main port
    ProxyPass / http://ebay_odoo:8069/
    ProxyPassReverse / http://ebay_odoo:8069/

    # SSL configuration
    SSLEngine on
    SSLCertificateFile /certs/SSL_CERTIFICATE_FILE.pem
    SSLCertificateKeyFile /certs/SSL_CERTIFICATE_KEY_FILE.pem

    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set X-XSS-Protection "1; mode=block"
    Header always set X-Content-Type-Options "nosniff"
    Header always set Referrer-Policy "no-referrer-when-downgrade"
    Header always set Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline' 'unsafe-eval'"
</VirtualHost>

<VirtualHost *:10001>
    ProxyPreserveHost On

    # Redirect ebay_helper requests
    ProxyPass / https://ebay_server:10001/
    ProxyPassReverse / https://ebay_server:10001/

    # Отключение проверки сертификатов
    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    
    # SSL configuration
    SSLEngine on
    SSLCertificateFile /certs/SSL_CERTIFICATE_FILE.pem
    SSLCertificateKeyFile /certs/SSL_CERTIFICATE_KEY_FILE.pem

    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set X-XSS-Protection "1; mode=block"
    Header always set X-Content-Type-Options "nosniff"
    Header always set Referrer-Policy "no-referrer-when-downgrade"
    Header always set Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline' 'unsafe-eval'"
</VirtualHost>