<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>ChromeExtension</RootNamespace>
        <Version>1.0.5</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NSwag.MSBuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <Target Name="NSwag" BeforeTargets="BeforeBuild">
        <Exec Command="$(NSwagExe_Net80) openapi2tsclient /input:../Server/Controllers/Contracts/Ebay.yaml /output:EbayClient/EbayToolBackendClient.ts /ClassName:EbayToolBackendClient"/>
        <Exec Command="powershell -Command &quot;$package = Get-Content package.json | ConvertFrom-Json; $package.version = '$(Version)'; $package | ConvertTo-Json -Depth 10 | Set-Content package.json&quot;" />
        <Exec Command="powershell -Command &quot;$manifest = Get-Content '_extension/manifest.json' | ConvertFrom-Json; $manifest.version = '$(Version)'; $manifest | ConvertTo-Json -Depth 10 | Set-Content '_extension/manifest.json'&quot;" />
        <Exec Command="npm run build" />
        <Exec Condition="!Exists('../Server/wwwroot/chrome_extensions/mlebgdemjnpnfgcgbbncllpniiicffbm_$(Version).crx')"
              Command="crx3 _extension --keyPath=./key.pem --crxPath=./../Server/wwwroot/chrome_extensions/mlebgdemjnpnfgcgbbncllpniiicffbm_$(Version).crx" />
    </Target>
    
</Project>
