<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="NUnit"/>
        <PackageReference Include="NUnit3TestAdapter"/>
        <PackageReference Include="NUnit.Analyzers"/>
        <PackageReference Include="coverlet.collector"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Server.Client\Server.Client.csproj" />
      <ProjectReference Include="..\Server\Server.csproj" />
      <ProjectReference Include="..\Server.Adapters.ChipFind\Server.Adapters.ChipFind.csproj" />
    </ItemGroup>

</Project>
