//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class EbayToolBackendClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "/api/ebay/v1";
    }

    /**
     * List all products
     * @return OK
     */
    getAllProducts(): Promise<ProductWithId[]> {
        let url_ = this.baseUrl + "/products";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAllProducts(_response);
        });
    }

    protected processGetAllProducts(response: Response): Promise<ProductWithId[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ProductWithId.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ProductWithId[]>(null as any);
    }

    /**
     * Create product
     * @return Updated
     */
    createProduct(product: ProductWithoutId): Promise<string> {
        let url_ = this.baseUrl + "/products";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(product);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateProduct(_response);
        });
    }

    protected processCreateProduct(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ValidationProblemDetailedInfo.fromJS(resultData400);
            return throwException("Error", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * Update product
     * @return Updated
     */
    updateProduct(product: ProductWithoutId, id: string): Promise<void> {
        let url_ = this.baseUrl + "/products/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(product);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateProduct(_response);
        });
    }

    protected processUpdateProduct(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ValidationProblemDetailedInfo.fromJS(resultData400);
            return throwException("Error", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Ok
     */
    getProduct(id: string): Promise<ProductWithId> {
        let url_ = this.baseUrl + "/products/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetProduct(_response);
        });
    }

    protected processGetProduct(response: Response): Promise<ProductWithId> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ProductWithId.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = NotFoundProblemDetailedInfo.fromJS(resultData400);
            return throwException("Error", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ProductWithId>(null as any);
    }

    /**
     * Delete product
     * @return Deleted
     */
    deleteProduct(id: string): Promise<void> {
        let url_ = this.baseUrl + "/products/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteProduct(_response);
        });
    }

    protected processDeleteProduct(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * MarkProductAsChecked
     * @return Updated
     */
    markProductAsChecked(id: string): Promise<void> {
        let url_ = this.baseUrl + "/products/{id}/mark_as_checked/";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMarkProductAsChecked(_response);
        });
    }

    protected processMarkProductAsChecked(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = NotFoundProblemDetailedInfo.fromJS(resultData400);
            return throwException("NotFound", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Ok
     */
    getLots(productId: string): Promise<LotInfoShort[]> {
        let url_ = this.baseUrl + "/products/{productId}/lots/";
        if (productId === undefined || productId === null)
            throw new Error("The parameter 'productId' must be defined.");
        url_ = url_.replace("{productId}", encodeURIComponent("" + productId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLots(_response);
        });
    }

    protected processGetLots(response: Response): Promise<LotInfoShort[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(LotInfoShort.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = NotFoundProblemDetailedInfo.fromJS(resultData400);
            return throwException("NotFound", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LotInfoShort[]>(null as any);
    }

    /**
     * Обновляет информацию о лоте
     * @return Ok
     */
    upsertLotInfo(lotInfo: LotInfo, productId: string): Promise<void> {
        let url_ = this.baseUrl + "/products/{productId}/lots/";
        if (productId === undefined || productId === null)
            throw new Error("The parameter 'productId' must be defined.");
        url_ = url_.replace("{productId}", encodeURIComponent("" + productId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(lotInfo);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpsertLotInfo(_response);
        });
    }

    protected processUpsertLotInfo(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ValidationProblemDetailedInfo.fromJS(resultData400);
            return throwException("NotFound", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Ok
     */
    getIgnoredLots(productId: string): Promise<number[]> {
        let url_ = this.baseUrl + "/products/{productId}/ignored_lots/";
        if (productId === undefined || productId === null)
            throw new Error("The parameter 'productId' must be defined.");
        url_ = url_.replace("{productId}", encodeURIComponent("" + productId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetIgnoredLots(_response);
        });
    }

    protected processGetIgnoredLots(response: Response): Promise<number[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(item);
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = NotFoundProblemDetailedInfo.fromJS(resultData400);
            return throwException("NotFound", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number[]>(null as any);
    }

    /**
     * @return Ok
     */
    ignoreLots(ignoredLots: number[], productId: string): Promise<void> {
        let url_ = this.baseUrl + "/products/{productId}/ignored_lots/";
        if (productId === undefined || productId === null)
            throw new Error("The parameter 'productId' must be defined.");
        url_ = url_.replace("{productId}", encodeURIComponent("" + productId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(ignoredLots);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processIgnoreLots(_response);
        });
    }

    protected processIgnoreLots(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = NotFoundProblemDetailedInfo.fromJS(resultData400);
            return throwException("NotFound", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Ok
     */
    getIsLotIgnoredForProduct(productId: string, lotId: number): Promise<boolean> {
        let url_ = this.baseUrl + "/products/{productId}/ignored_lots/{lotId}";
        if (productId === undefined || productId === null)
            throw new Error("The parameter 'productId' must be defined.");
        url_ = url_.replace("{productId}", encodeURIComponent("" + productId));
        if (lotId === undefined || lotId === null)
            throw new Error("The parameter 'lotId' must be defined.");
        url_ = url_.replace("{lotId}", encodeURIComponent("" + lotId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetIsLotIgnoredForProduct(_response);
        });
    }

    protected processGetIsLotIgnoredForProduct(response: Response): Promise<boolean> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = NotFoundProblemDetailedInfo.fromJS(resultData400);
            return throwException("NotFound", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<boolean>(null as any);
    }

    /**
     * @return Ok
     */
    calculatePricesForProduct(productId: string): Promise<void> {
        let url_ = this.baseUrl + "/products/{productId}/calculate_prices/";
        if (productId === undefined || productId === null)
            throw new Error("The parameter 'productId' must be defined.");
        url_ = url_.replace("{productId}", encodeURIComponent("" + productId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCalculatePricesForProduct(_response);
        });
    }

    protected processCalculatePricesForProduct(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Ok
     */
    getMeasurements(productId: string): Promise<MeasurementData[]> {
        let url_ = this.baseUrl + "/products/{productId}/measurements/";
        if (productId === undefined || productId === null)
            throw new Error("The parameter 'productId' must be defined.");
        url_ = url_.replace("{productId}", encodeURIComponent("" + productId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetMeasurements(_response);
        });
    }

    protected processGetMeasurements(response: Response): Promise<MeasurementData[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(MeasurementData.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MeasurementData[]>(null as any);
    }

    /**
     * @return Ok
     */
    uploadMeasurement(measurementData: MeasurementDataToUpload, productId: string): Promise<void> {
        let url_ = this.baseUrl + "/products/{productId}/measurements/";
        if (productId === undefined || productId === null)
            throw new Error("The parameter 'productId' must be defined.");
        url_ = url_.replace("{productId}", encodeURIComponent("" + productId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(measurementData);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUploadMeasurement(_response);
        });
    }

    protected processUploadMeasurement(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ValidationProblemDetailedInfo.fromJS(resultData400);
            return throwException("InvalidMeasurement", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Получить информацию о лоте
     * @return Ok
     */
    getLotInfo(lotId: number): Promise<LotInfoWithProductId> {
        let url_ = this.baseUrl + "/lots/{lotId}/";
        if (lotId === undefined || lotId === null)
            throw new Error("The parameter 'lotId' must be defined.");
        url_ = url_.replace("{lotId}", encodeURIComponent("" + lotId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLotInfo(_response);
        });
    }

    protected processGetLotInfo(response: Response): Promise<LotInfoWithProductId> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = LotInfoWithProductId.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = NotFoundProblemDetailedInfo.fromJS(resultData400);
            return throwException("NotFound", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LotInfoWithProductId>(null as any);
    }

    /**
     * Удалить информацию о лоте
     * @return Ok
     */
    deleteLotInfo(lotId: number): Promise<void> {
        let url_ = this.baseUrl + "/lots/{lotId}/";
        if (lotId === undefined || lotId === null)
            throw new Error("The parameter 'lotId' must be defined.");
        url_ = url_.replace("{lotId}", encodeURIComponent("" + lotId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteLotInfo(_response);
        });
    }

    protected processDeleteLotInfo(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = NotFoundProblemDetailedInfo.fromJS(resultData400);
            return throwException("NotFound", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Получить id всех лотов
     * @return Ok
     */
    getLotIds(): Promise<number[]> {
        let url_ = this.baseUrl + "/lots/";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLotIds(_response);
        });
    }

    protected processGetLotIds(response: Response): Promise<number[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(item);
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<number[]>(null as any);
    }

    /**
     * Получает информацию о учтенных лотах
     * @return Ok
     */
    getLotStates(lotIds: number[]): Promise<LotState[]> {
        let url_ = this.baseUrl + "/lot_state_requests/";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(lotIds);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetLotStates(_response);
        });
    }

    protected processGetLotStates(response: Response): Promise<LotState[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(LotState.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LotState[]>(null as any);
    }

    /**
     * @return Ok
     */
    getCategories(): Promise<CategoryType[]> {
        let url_ = this.baseUrl + "/categories/";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetCategories(_response);
        });
    }

    protected processGetCategories(response: Response): Promise<CategoryType[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(CategoryType.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CategoryType[]>(null as any);
    }

    /**
     * @return Ok
     */
    getShippingRates(): Promise<ShippingType[]> {
        let url_ = this.baseUrl + "/shipping_rates/";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetShippingRates(_response);
        });
    }

    protected processGetShippingRates(response: Response): Promise<ShippingType[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ShippingType.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ShippingType[]>(null as any);
    }

    /**
     * @return Ok
     */
    getCurrencies(): Promise<Currency[]> {
        let url_ = this.baseUrl + "/currencies/";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetCurrencies(_response);
        });
    }

    protected processGetCurrencies(response: Response): Promise<Currency[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(Currency.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Currency[]>(null as any);
    }

    /**
     * Извлекает информацию о лоте из названия и описания
     * @return Ok
     */
    extractData(lotInfo: LotDataToExtract): Promise<ExtractedFields[]> {
        let url_ = this.baseUrl + "/extract_data/";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(lotInfo);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processExtractData(_response);
        });
    }

    protected processExtractData(response: Response): Promise<ExtractedFields[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ExtractedFields.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ExtractedFields[]>(null as any);
    }

    /**
     * Save Error
     * @return Ok
     */
    saveError(error: ClientErrorInfo): Promise<void> {
        let url_ = this.baseUrl + "/error/";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(error);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSaveError(_response);
        });
    }

    protected processSaveError(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Ok
     */
    calculatePricesForAll(): Promise<void> {
        let url_ = this.baseUrl + "/calculate_prices_for_all/";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCalculatePricesForAll(_response);
        });
    }

    protected processCalculatePricesForAll(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export enum ProductState {
    New = "New",
    Used = "Used",
}

export class ProductWithoutId implements IProductWithoutId {
    name!: string;
    searchQueries!: SearchQuery[];
    ruSearchQueries!: RuSearchQuery[];
    weight!: number;

    constructor(data?: IProductWithoutId) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.searchQueries = [];
            this.ruSearchQueries = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["Name"];
            if (Array.isArray(_data["SearchQueries"])) {
                this.searchQueries = [] as any;
                for (let item of _data["SearchQueries"])
                    this.searchQueries!.push(SearchQuery.fromJS(item));
            }
            if (Array.isArray(_data["RuSearchQueries"])) {
                this.ruSearchQueries = [] as any;
                for (let item of _data["RuSearchQueries"])
                    this.ruSearchQueries!.push(RuSearchQuery.fromJS(item));
            }
            this.weight = _data["Weight"];
        }
    }

    static fromJS(data: any): ProductWithoutId {
        data = typeof data === 'object' ? data : {};
        let result = new ProductWithoutId();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Name"] = this.name;
        if (Array.isArray(this.searchQueries)) {
            data["SearchQueries"] = [];
            for (let item of this.searchQueries)
                data["SearchQueries"].push(item.toJSON());
        }
        if (Array.isArray(this.ruSearchQueries)) {
            data["RuSearchQueries"] = [];
            for (let item of this.ruSearchQueries)
                data["RuSearchQueries"].push(item.toJSON());
        }
        data["Weight"] = this.weight;
        return data;
    }
}

export interface IProductWithoutId {
    name: string;
    searchQueries: SearchQuery[];
    ruSearchQueries: RuSearchQuery[];
    weight: number;
}

export class ProductWithId implements IProductWithId {
    id!: string;
    name!: string;
    isCheckRequired!: boolean;
    weight!: number;
    searchQueries!: SearchQuery[];
    ruSearchQueries!: RuSearchQuery[];
    productCalculationResult?: ProductCalculationResult | undefined;

    constructor(data?: IProductWithId) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.searchQueries = [];
            this.ruSearchQueries = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.name = _data["Name"];
            this.isCheckRequired = _data["IsCheckRequired"];
            this.weight = _data["Weight"];
            if (Array.isArray(_data["SearchQueries"])) {
                this.searchQueries = [] as any;
                for (let item of _data["SearchQueries"])
                    this.searchQueries!.push(SearchQuery.fromJS(item));
            }
            if (Array.isArray(_data["RuSearchQueries"])) {
                this.ruSearchQueries = [] as any;
                for (let item of _data["RuSearchQueries"])
                    this.ruSearchQueries!.push(RuSearchQuery.fromJS(item));
            }
            this.productCalculationResult = _data["ProductCalculationResult"] ? ProductCalculationResult.fromJS(_data["ProductCalculationResult"]) : <any>undefined;
        }
    }

    static fromJS(data: any): ProductWithId {
        data = typeof data === 'object' ? data : {};
        let result = new ProductWithId();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Name"] = this.name;
        data["IsCheckRequired"] = this.isCheckRequired;
        data["Weight"] = this.weight;
        if (Array.isArray(this.searchQueries)) {
            data["SearchQueries"] = [];
            for (let item of this.searchQueries)
                data["SearchQueries"].push(item.toJSON());
        }
        if (Array.isArray(this.ruSearchQueries)) {
            data["RuSearchQueries"] = [];
            for (let item of this.ruSearchQueries)
                data["RuSearchQueries"].push(item.toJSON());
        }
        data["ProductCalculationResult"] = this.productCalculationResult ? this.productCalculationResult.toJSON() : <any>undefined;
        return data;
    }
}

export interface IProductWithId {
    id: string;
    name: string;
    isCheckRequired: boolean;
    weight: number;
    searchQueries: SearchQuery[];
    ruSearchQueries: RuSearchQuery[];
    productCalculationResult?: ProductCalculationResult | undefined;
}

export class SearchQuery implements ISearchQuery {
    id!: string;
    query!: string;

    constructor(data?: ISearchQuery) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.query = _data["query"];
        }
    }

    static fromJS(data: any): SearchQuery {
        data = typeof data === 'object' ? data : {};
        let result = new SearchQuery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["query"] = this.query;
        return data;
    }
}

export interface ISearchQuery {
    id: string;
    query: string;
}

export class RuSearchQuery implements IRuSearchQuery {
    id!: string;
    query!: string;

    constructor(data?: IRuSearchQuery) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.query = _data["query"];
        }
    }

    static fromJS(data: any): RuSearchQuery {
        data = typeof data === 'object' ? data : {};
        let result = new RuSearchQuery();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["query"] = this.query;
        return data;
    }
}

export interface IRuSearchQuery {
    id: string;
    query: string;
}

export class LotInfoWithProductId implements ILotInfoWithProductId {
    productId!: string;
    lotInfo!: LotInfo;

    constructor(data?: ILotInfoWithProductId) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.lotInfo = new LotInfo();
        }
    }

    init(_data?: any) {
        if (_data) {
            this.productId = _data["productId"];
            this.lotInfo = _data["lotInfo"] ? LotInfo.fromJS(_data["lotInfo"]) : new LotInfo();
        }
    }

    static fromJS(data: any): LotInfoWithProductId {
        data = typeof data === 'object' ? data : {};
        let result = new LotInfoWithProductId();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["productId"] = this.productId;
        data["lotInfo"] = this.lotInfo ? this.lotInfo.toJSON() : <any>undefined;
        return data;
    }
}

export interface ILotInfoWithProductId {
    productId: string;
    lotInfo: LotInfo;
}

export class MeasurementData implements IMeasurementData {
    measurementId!: string;
    manufactureDate!: string;
    productState!: ProductState;

    constructor(data?: IMeasurementData) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.measurementId = _data["measurementId"];
            this.manufactureDate = _data["manufactureDate"];
            this.productState = _data["productState"];
        }
    }

    static fromJS(data: any): MeasurementData {
        data = typeof data === 'object' ? data : {};
        let result = new MeasurementData();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["measurementId"] = this.measurementId;
        data["manufactureDate"] = this.manufactureDate;
        data["productState"] = this.productState;
        return data;
    }
}

export interface IMeasurementData {
    measurementId: string;
    manufactureDate: string;
    productState: ProductState;
}

export class MeasurementDataToUpload implements IMeasurementDataToUpload {
    measurementId!: string;
    manufactureDate!: string;
    productState!: ProductState;
    file!: string;

    constructor(data?: IMeasurementDataToUpload) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.measurementId = _data["measurementId"];
            this.manufactureDate = _data["manufactureDate"];
            this.productState = _data["productState"];
            this.file = _data["file"];
        }
    }

    static fromJS(data: any): MeasurementDataToUpload {
        data = typeof data === 'object' ? data : {};
        let result = new MeasurementDataToUpload();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["measurementId"] = this.measurementId;
        data["manufactureDate"] = this.manufactureDate;
        data["productState"] = this.productState;
        data["file"] = this.file;
        return data;
    }
}

export interface IMeasurementDataToUpload {
    measurementId: string;
    manufactureDate: string;
    productState: ProductState;
    file: string;
}

export class LotInfo implements ILotInfo {
    lotId!: number;
    name!: string;
    pcs!: number;
    lotSize?: number | undefined;
    shippingCountry!: string;
    currency!: string;
    price!: number;
    shipping?: number | undefined;
    shippingAdditional?: number | undefined;
    description!: string;
    condition!: string;
    conditionDescription?: string | undefined;
    shortDescription?: string | undefined;
    seller!: string;
    locatedIn!: string;
    categories!: CategoryValue[];
    titleChangeDate!: string;
    purchaseHistory!: PurchaseInfo[];

    constructor(data?: ILotInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.categories = [];
            this.purchaseHistory = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.lotId = _data["lotId"];
            this.name = _data["name"];
            this.pcs = _data["pcs"];
            this.lotSize = _data["lotSize"];
            this.shippingCountry = _data["shippingCountry"];
            this.currency = _data["currency"];
            this.price = _data["price"];
            this.shipping = _data["shipping"];
            this.shippingAdditional = _data["shippingAdditional"];
            this.description = _data["description"];
            this.condition = _data["condition"];
            this.conditionDescription = _data["conditionDescription"];
            this.shortDescription = _data["shortDescription"];
            this.seller = _data["seller"];
            this.locatedIn = _data["locatedIn"];
            if (Array.isArray(_data["categories"])) {
                this.categories = [] as any;
                for (let item of _data["categories"])
                    this.categories!.push(CategoryValue.fromJS(item));
            }
            this.titleChangeDate = _data["titleChangeDate"];
            if (Array.isArray(_data["purchaseHistory"])) {
                this.purchaseHistory = [] as any;
                for (let item of _data["purchaseHistory"])
                    this.purchaseHistory!.push(PurchaseInfo.fromJS(item));
            }
        }
    }

    static fromJS(data: any): LotInfo {
        data = typeof data === 'object' ? data : {};
        let result = new LotInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["lotId"] = this.lotId;
        data["name"] = this.name;
        data["pcs"] = this.pcs;
        data["lotSize"] = this.lotSize;
        data["shippingCountry"] = this.shippingCountry;
        data["currency"] = this.currency;
        data["price"] = this.price;
        data["shipping"] = this.shipping;
        data["shippingAdditional"] = this.shippingAdditional;
        data["description"] = this.description;
        data["condition"] = this.condition;
        data["conditionDescription"] = this.conditionDescription;
        data["shortDescription"] = this.shortDescription;
        data["seller"] = this.seller;
        data["locatedIn"] = this.locatedIn;
        if (Array.isArray(this.categories)) {
            data["categories"] = [];
            for (let item of this.categories)
                data["categories"].push(item.toJSON());
        }
        data["titleChangeDate"] = this.titleChangeDate;
        if (Array.isArray(this.purchaseHistory)) {
            data["purchaseHistory"] = [];
            for (let item of this.purchaseHistory)
                data["purchaseHistory"].push(item.toJSON());
        }
        return data;
    }
}

export interface ILotInfo {
    lotId: number;
    name: string;
    pcs: number;
    lotSize?: number | undefined;
    shippingCountry: string;
    currency: string;
    price: number;
    shipping?: number | undefined;
    shippingAdditional?: number | undefined;
    description: string;
    condition: string;
    conditionDescription?: string | undefined;
    shortDescription?: string | undefined;
    seller: string;
    locatedIn: string;
    categories: CategoryValue[];
    titleChangeDate: string;
    purchaseHistory: PurchaseInfo[];
}

export class LotInfoShort implements ILotInfoShort {
    lotId!: number;
    name!: string;
    pcs!: number;
    shippingCountry!: string;
    currency!: string;
    price!: number;
    shipping?: number | undefined;
    shippingAdditional?: number | undefined;
    condition!: string;
    conditionDescription?: string | undefined;
    shortDescription?: string | undefined;
    seller!: string;
    locatedIn!: string;
    categories!: CategoryValue[];
    titleChangeDate!: string;
    purchaseHistory!: PurchaseInfo[];
    lotCalculationResult?: LotCalculationResult | undefined;

    constructor(data?: ILotInfoShort) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.categories = [];
            this.purchaseHistory = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.lotId = _data["lotId"];
            this.name = _data["name"];
            this.pcs = _data["pcs"];
            this.shippingCountry = _data["shippingCountry"];
            this.currency = _data["currency"];
            this.price = _data["price"];
            this.shipping = _data["shipping"];
            this.shippingAdditional = _data["shippingAdditional"];
            this.condition = _data["condition"];
            this.conditionDescription = _data["conditionDescription"];
            this.shortDescription = _data["shortDescription"];
            this.seller = _data["seller"];
            this.locatedIn = _data["locatedIn"];
            if (Array.isArray(_data["categories"])) {
                this.categories = [] as any;
                for (let item of _data["categories"])
                    this.categories!.push(CategoryValue.fromJS(item));
            }
            this.titleChangeDate = _data["titleChangeDate"];
            if (Array.isArray(_data["purchaseHistory"])) {
                this.purchaseHistory = [] as any;
                for (let item of _data["purchaseHistory"])
                    this.purchaseHistory!.push(PurchaseInfo.fromJS(item));
            }
            this.lotCalculationResult = _data["lotCalculationResult"] ? LotCalculationResult.fromJS(_data["lotCalculationResult"]) : <any>undefined;
        }
    }

    static fromJS(data: any): LotInfoShort {
        data = typeof data === 'object' ? data : {};
        let result = new LotInfoShort();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["lotId"] = this.lotId;
        data["name"] = this.name;
        data["pcs"] = this.pcs;
        data["shippingCountry"] = this.shippingCountry;
        data["currency"] = this.currency;
        data["price"] = this.price;
        data["shipping"] = this.shipping;
        data["shippingAdditional"] = this.shippingAdditional;
        data["condition"] = this.condition;
        data["conditionDescription"] = this.conditionDescription;
        data["shortDescription"] = this.shortDescription;
        data["seller"] = this.seller;
        data["locatedIn"] = this.locatedIn;
        if (Array.isArray(this.categories)) {
            data["categories"] = [];
            for (let item of this.categories)
                data["categories"].push(item.toJSON());
        }
        data["titleChangeDate"] = this.titleChangeDate;
        if (Array.isArray(this.purchaseHistory)) {
            data["purchaseHistory"] = [];
            for (let item of this.purchaseHistory)
                data["purchaseHistory"].push(item.toJSON());
        }
        data["lotCalculationResult"] = this.lotCalculationResult ? this.lotCalculationResult.toJSON() : <any>undefined;
        return data;
    }
}

export interface ILotInfoShort {
    lotId: number;
    name: string;
    pcs: number;
    shippingCountry: string;
    currency: string;
    price: number;
    shipping?: number | undefined;
    shippingAdditional?: number | undefined;
    condition: string;
    conditionDescription?: string | undefined;
    shortDescription?: string | undefined;
    seller: string;
    locatedIn: string;
    categories: CategoryValue[];
    titleChangeDate: string;
    purchaseHistory: PurchaseInfo[];
    lotCalculationResult?: LotCalculationResult | undefined;
}

export class ProductCalculationResult implements IProductCalculationResult {
    revenue!: number;
    quantityTotal!: number;
    revenueAvg!: number;
    calculationDate!: string;

    constructor(data?: IProductCalculationResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.revenue = _data["revenue"];
            this.quantityTotal = _data["quantityTotal"];
            this.revenueAvg = _data["revenueAvg"];
            this.calculationDate = _data["calculationDate"];
        }
    }

    static fromJS(data: any): ProductCalculationResult {
        data = typeof data === 'object' ? data : {};
        let result = new ProductCalculationResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["revenue"] = this.revenue;
        data["quantityTotal"] = this.quantityTotal;
        data["revenueAvg"] = this.revenueAvg;
        data["calculationDate"] = this.calculationDate;
        return data;
    }
}

export interface IProductCalculationResult {
    revenue: number;
    quantityTotal: number;
    revenueAvg: number;
    calculationDate: string;
}

export class LotCalculationResult implements ILotCalculationResult {
    revenue!: number;
    quantityTotal!: number;
    revenueAvg!: number;
    calculationDate!: string;

    constructor(data?: ILotCalculationResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.revenue = _data["revenue"];
            this.quantityTotal = _data["quantityTotal"];
            this.revenueAvg = _data["revenueAvg"];
            this.calculationDate = _data["calculationDate"];
        }
    }

    static fromJS(data: any): LotCalculationResult {
        data = typeof data === 'object' ? data : {};
        let result = new LotCalculationResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["revenue"] = this.revenue;
        data["quantityTotal"] = this.quantityTotal;
        data["revenueAvg"] = this.revenueAvg;
        data["calculationDate"] = this.calculationDate;
        return data;
    }
}

export interface ILotCalculationResult {
    revenue: number;
    quantityTotal: number;
    revenueAvg: number;
    calculationDate: string;
}

export class PurchaseInfo implements IPurchaseInfo {
    price?: number | undefined;
    quantity!: number;
    date!: string;
    purchaseCalculationResult?: PurchaseCalculationResult | undefined;

    constructor(data?: IPurchaseInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.price = _data["price"];
            this.quantity = _data["quantity"];
            this.date = _data["date"];
            this.purchaseCalculationResult = _data["purchaseCalculationResult"] ? PurchaseCalculationResult.fromJS(_data["purchaseCalculationResult"]) : <any>undefined;
        }
    }

    static fromJS(data: any): PurchaseInfo {
        data = typeof data === 'object' ? data : {};
        let result = new PurchaseInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["price"] = this.price;
        data["quantity"] = this.quantity;
        data["date"] = this.date;
        data["purchaseCalculationResult"] = this.purchaseCalculationResult ? this.purchaseCalculationResult.toJSON() : <any>undefined;
        return data;
    }
}

export interface IPurchaseInfo {
    price?: number | undefined;
    quantity: number;
    date: string;
    purchaseCalculationResult?: PurchaseCalculationResult | undefined;
}

export class PurchaseCalculationResult implements IPurchaseCalculationResult {
    revenue!: number;
    quantityTotal!: number;
    revenueAvg!: number;

    constructor(data?: IPurchaseCalculationResult) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.revenue = _data["revenue"];
            this.quantityTotal = _data["quantityTotal"];
            this.revenueAvg = _data["revenueAvg"];
        }
    }

    static fromJS(data: any): PurchaseCalculationResult {
        data = typeof data === 'object' ? data : {};
        let result = new PurchaseCalculationResult();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["revenue"] = this.revenue;
        data["quantityTotal"] = this.quantityTotal;
        data["revenueAvg"] = this.revenueAvg;
        return data;
    }
}

export interface IPurchaseCalculationResult {
    revenue: number;
    quantityTotal: number;
    revenueAvg: number;
}

export class CategoryValue implements ICategoryValue {
    type!: string;
    value!: string;

    constructor(data?: ICategoryValue) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): CategoryValue {
        data = typeof data === 'object' ? data : {};
        let result = new CategoryValue();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["value"] = this.value;
        return data;
    }
}

export interface ICategoryValue {
    type: string;
    value: string;
}

export class CategoryType implements ICategoryType {
    type!: string;
    items!: CategoryItem[];

    constructor(data?: ICategoryType) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.items = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(CategoryItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CategoryType {
        data = typeof data === 'object' ? data : {};
        let result = new CategoryType();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item.toJSON());
        }
        return data;
    }
}

export interface ICategoryType {
    type: string;
    items: CategoryItem[];
}

export class CategoryItem implements ICategoryItem {
    id!: string;
    description!: string;

    constructor(data?: ICategoryItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.description = _data["description"];
        }
    }

    static fromJS(data: any): CategoryItem {
        data = typeof data === 'object' ? data : {};
        let result = new CategoryItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["description"] = this.description;
        return data;
    }
}

export interface ICategoryItem {
    id: string;
    description: string;
}

export class LotDataToExtract implements ILotDataToExtract {
    name!: string;
    condition!: string;
    conditionDescription?: string | undefined;
    description!: string;
    shortDescription?: string | undefined;
    lotSize?: number | undefined;

    constructor(data?: ILotDataToExtract) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.condition = _data["condition"];
            this.conditionDescription = _data["conditionDescription"];
            this.description = _data["description"];
            this.shortDescription = _data["shortDescription"];
            this.lotSize = _data["lotSize"];
        }
    }

    static fromJS(data: any): LotDataToExtract {
        data = typeof data === 'object' ? data : {};
        let result = new LotDataToExtract();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["condition"] = this.condition;
        data["conditionDescription"] = this.conditionDescription;
        data["description"] = this.description;
        data["shortDescription"] = this.shortDescription;
        data["lotSize"] = this.lotSize;
        return data;
    }
}

export interface ILotDataToExtract {
    name: string;
    condition: string;
    conditionDescription?: string | undefined;
    description: string;
    shortDescription?: string | undefined;
    lotSize?: number | undefined;
}

export class ExtractedFields implements IExtractedFields {
    fieldName!: string;
    extractedData!: LotDataExtractedItem[];

    constructor(data?: IExtractedFields) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.extractedData = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.fieldName = _data["fieldName"];
            if (Array.isArray(_data["extractedData"])) {
                this.extractedData = [] as any;
                for (let item of _data["extractedData"])
                    this.extractedData!.push(LotDataExtractedItem.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ExtractedFields {
        data = typeof data === 'object' ? data : {};
        let result = new ExtractedFields();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["fieldName"] = this.fieldName;
        if (Array.isArray(this.extractedData)) {
            data["extractedData"] = [];
            for (let item of this.extractedData)
                data["extractedData"].push(item.toJSON());
        }
        return data;
    }
}

export interface IExtractedFields {
    fieldName: string;
    extractedData: LotDataExtractedItem[];
}

export class LotDataExtractedItem implements ILotDataExtractedItem {
    value!: string;
    extractorInfo!: ExtractorInfo[];

    constructor(data?: ILotDataExtractedItem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.extractorInfo = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.value = _data["value"];
            if (Array.isArray(_data["extractorInfo"])) {
                this.extractorInfo = [] as any;
                for (let item of _data["extractorInfo"])
                    this.extractorInfo!.push(ExtractorInfo.fromJS(item));
            }
        }
    }

    static fromJS(data: any): LotDataExtractedItem {
        data = typeof data === 'object' ? data : {};
        let result = new LotDataExtractedItem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["value"] = this.value;
        if (Array.isArray(this.extractorInfo)) {
            data["extractorInfo"] = [];
            for (let item of this.extractorInfo)
                data["extractorInfo"].push(item.toJSON());
        }
        return data;
    }
}

export interface ILotDataExtractedItem {
    value: string;
    extractorInfo: ExtractorInfo[];
}

export class ExtractorInfo implements IExtractorInfo {
    extractedFrom!: string;
    extractor!: string;
    match!: string;

    constructor(data?: IExtractorInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.extractedFrom = _data["extractedFrom"];
            this.extractor = _data["extractor"];
            this.match = _data["match"];
        }
    }

    static fromJS(data: any): ExtractorInfo {
        data = typeof data === 'object' ? data : {};
        let result = new ExtractorInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["extractedFrom"] = this.extractedFrom;
        data["extractor"] = this.extractor;
        data["match"] = this.match;
        return data;
    }
}

export interface IExtractorInfo {
    extractedFrom: string;
    extractor: string;
    match: string;
}

export class LotState implements ILotState {
    lotId!: number;
    lastUpdate!: string;

    constructor(data?: ILotState) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.lotId = _data["lotId"];
            this.lastUpdate = _data["lastUpdate"];
        }
    }

    static fromJS(data: any): LotState {
        data = typeof data === 'object' ? data : {};
        let result = new LotState();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["lotId"] = this.lotId;
        data["lastUpdate"] = this.lastUpdate;
        return data;
    }
}

export interface ILotState {
    lotId: number;
    lastUpdate: string;
}

export class ClientErrorInfo implements IClientErrorInfo {
    url!: string;
    error!: string;

    constructor(data?: IClientErrorInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.url = _data["url"];
            this.error = _data["error"];
        }
    }

    static fromJS(data: any): ClientErrorInfo {
        data = typeof data === 'object' ? data : {};
        let result = new ClientErrorInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["url"] = this.url;
        data["error"] = this.error;
        return data;
    }
}

export interface IClientErrorInfo {
    url: string;
    error: string;
}

export class ShippingType implements IShippingType {
    name!: string;
    currency!: string;
    rates!: ShippingRates[];

    constructor(data?: IShippingType) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.rates = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.currency = _data["currency"];
            if (Array.isArray(_data["rates"])) {
                this.rates = [] as any;
                for (let item of _data["rates"])
                    this.rates!.push(ShippingRates.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ShippingType {
        data = typeof data === 'object' ? data : {};
        let result = new ShippingType();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["currency"] = this.currency;
        if (Array.isArray(this.rates)) {
            data["rates"] = [];
            for (let item of this.rates)
                data["rates"].push(item.toJSON());
        }
        return data;
    }
}

export interface IShippingType {
    name: string;
    currency: string;
    rates: ShippingRates[];
}

export class ShippingRates implements IShippingRates {
    specifiedCountries?: string[] | undefined;
    rates!: ShippingRate[];

    constructor(data?: IShippingRates) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.rates = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["specifiedCountries"])) {
                this.specifiedCountries = [] as any;
                for (let item of _data["specifiedCountries"])
                    this.specifiedCountries!.push(item);
            }
            if (Array.isArray(_data["rates"])) {
                this.rates = [] as any;
                for (let item of _data["rates"])
                    this.rates!.push(ShippingRate.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ShippingRates {
        data = typeof data === 'object' ? data : {};
        let result = new ShippingRates();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.specifiedCountries)) {
            data["specifiedCountries"] = [];
            for (let item of this.specifiedCountries)
                data["specifiedCountries"].push(item);
        }
        if (Array.isArray(this.rates)) {
            data["rates"] = [];
            for (let item of this.rates)
                data["rates"].push(item.toJSON());
        }
        return data;
    }
}

export interface IShippingRates {
    specifiedCountries?: string[] | undefined;
    rates: ShippingRate[];
}

export class ShippingRate implements IShippingRate {
    minWeight!: number;
    maxWeight!: number;
    price!: number;

    constructor(data?: IShippingRate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.minWeight = _data["minWeight"];
            this.maxWeight = _data["maxWeight"];
            this.price = _data["price"];
        }
    }

    static fromJS(data: any): ShippingRate {
        data = typeof data === 'object' ? data : {};
        let result = new ShippingRate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["minWeight"] = this.minWeight;
        data["maxWeight"] = this.maxWeight;
        data["price"] = this.price;
        return data;
    }
}

export interface IShippingRate {
    minWeight: number;
    maxWeight: number;
    price: number;
}

export class Currency implements ICurrency {
    ebayName!: string;
    rusName!: string;
    rate!: number;
    lastUpdate!: string;

    constructor(data?: ICurrency) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.ebayName = _data["ebayName"];
            this.rusName = _data["rusName"];
            this.rate = _data["rate"];
            this.lastUpdate = _data["lastUpdate"];
        }
    }

    static fromJS(data: any): Currency {
        data = typeof data === 'object' ? data : {};
        let result = new Currency();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ebayName"] = this.ebayName;
        data["rusName"] = this.rusName;
        data["rate"] = this.rate;
        data["lastUpdate"] = this.lastUpdate;
        return data;
    }
}

export interface ICurrency {
    ebayName: string;
    rusName: string;
    rate: number;
    lastUpdate: string;
}

export class Purchases implements IPurchases {
    conditions?: string[] | undefined;
    testStates?: string[] | undefined;
    itemsInPurchase!: number[];
    profitPerPcs!: number[];

    constructor(data?: IPurchases) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
        if (!data) {
            this.itemsInPurchase = [];
            this.profitPerPcs = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["conditions"])) {
                this.conditions = [] as any;
                for (let item of _data["conditions"])
                    this.conditions!.push(item);
            }
            if (Array.isArray(_data["testStates"])) {
                this.testStates = [] as any;
                for (let item of _data["testStates"])
                    this.testStates!.push(item);
            }
            if (Array.isArray(_data["itemsInPurchase"])) {
                this.itemsInPurchase = [] as any;
                for (let item of _data["itemsInPurchase"])
                    this.itemsInPurchase!.push(item);
            }
            if (Array.isArray(_data["profitPerPcs"])) {
                this.profitPerPcs = [] as any;
                for (let item of _data["profitPerPcs"])
                    this.profitPerPcs!.push(item);
            }
        }
    }

    static fromJS(data: any): Purchases {
        data = typeof data === 'object' ? data : {};
        let result = new Purchases();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.conditions)) {
            data["conditions"] = [];
            for (let item of this.conditions)
                data["conditions"].push(item);
        }
        if (Array.isArray(this.testStates)) {
            data["testStates"] = [];
            for (let item of this.testStates)
                data["testStates"].push(item);
        }
        if (Array.isArray(this.itemsInPurchase)) {
            data["itemsInPurchase"] = [];
            for (let item of this.itemsInPurchase)
                data["itemsInPurchase"].push(item);
        }
        if (Array.isArray(this.profitPerPcs)) {
            data["profitPerPcs"] = [];
            for (let item of this.profitPerPcs)
                data["profitPerPcs"].push(item);
        }
        return data;
    }
}

export interface IPurchases {
    conditions?: string[] | undefined;
    testStates?: string[] | undefined;
    itemsInPurchase: number[];
    profitPerPcs: number[];
}

export abstract class ProblemDetailedInfo implements IProblemDetailedInfo {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    constructor(data?: IProblemDetailedInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetailedInfo {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'ProblemDetailedInfo' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetailedInfo {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
}

export class NotFoundProblemDetailedInfo extends ProblemDetailedInfo implements INotFoundProblemDetailedInfo {
    errors?: Errors | undefined;

    constructor(data?: INotFoundProblemDetailedInfo) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.errors = _data["errors"];
        }
    }

    static fromJS(data: any): NotFoundProblemDetailedInfo {
        data = typeof data === 'object' ? data : {};
        let result = new NotFoundProblemDetailedInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["errors"] = this.errors;
        super.toJSON(data);
        return data;
    }
}

export interface INotFoundProblemDetailedInfo extends IProblemDetailedInfo {
    errors?: Errors | undefined;
}

export class ValidationProblemDetailedInfo extends ProblemDetailedInfo implements IValidationProblemDetailedInfo {
    errors?: errors | undefined;

    constructor(data?: IValidationProblemDetailedInfo) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.errors = _data["errors"];
        }
    }

    static fromJS(data: any): ValidationProblemDetailedInfo {
        data = typeof data === 'object' ? data : {};
        let result = new ValidationProblemDetailedInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["errors"] = this.errors;
        super.toJSON(data);
        return data;
    }
}

export interface IValidationProblemDetailedInfo extends IProblemDetailedInfo {
    errors?: errors | undefined;
}

export class Errors implements IErrors {

    [key: string]: any;

    constructor(data?: IErrors) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
        }
    }

    static fromJS(data: any): Errors {
        data = typeof data === 'object' ? data : {};
        let result = new Errors();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        return data;
    }
}

export interface IErrors {

    [key: string]: any;
}

export class errors implements Ierrors {

    [key: string]: any;

    constructor(data?: Ierrors) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
        }
    }

    static fromJS(data: any): errors {
        data = typeof data === 'object' ? data : {};
        let result = new errors();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        return data;
    }
}

export interface Ierrors {

    [key: string]: any;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}