<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <PackageReference Include="DotNetEnv" />
      <PackageReference Include="MailKit" />
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Server.Application.Legacy\Server.Application.Legacy.csproj" />
    </ItemGroup>

</Project>
