receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  transform:
  transform/level:
    log_statements:
      - context: log
        statements:
          - set(attributes["level"], "TRACE") where severity_number == 1
          - set(attributes["level"], "DEBUG") where severity_number == 5
          - set(attributes["level"], "INFO")  where severity_number == 9
          - set(attributes["level"], "WARN")  where severity_number == 13
          - set(attributes["level"], "ERROR") where severity_number == 17
          - set(attributes["level"], "FATAL") where severity_number == 21

  groupbyattrs/level:
    keys: ["level"]

  transform/promote_level:
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["level"], attributes["level"]) where attributes["level"] != nil
          - delete_key(attributes, "level")
  batch: {}

exporters:
  otlphttp/loki:
    endpoint: http://ebay_loki:3100/otlp
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [transform/level, groupbyattrs/level, transform/promote_level, batch]
      exporters: [debug, otlphttp/loki]