version: "3"

services:
  ebay_postgres:
    container_name: ebay_postgres
    image: postgres:16.1
    ports:
      - "15432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_INITDB_ARGS: --locale='en_US.UTF8'
      CFG_TIMEZONE: 'Europe/Moscow'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ebay_internal_network

  ebay_helper:
    container_name: ebay_helper
    image: ghcr.io/artyompetrov/ebay:latest
    ports:
      - "10001:10001"
    depends_on:
      - ebay_postgres
    restart: unless-stopped
    volumes:
      - ${NETCORE_CERTIFICATE}:/certs/cert.pfx:ro
    environment:
      - DOMAIN=${DOMAIN}
      - ASPNETCORE_URLS=https://+:10001/
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${NETCORE_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/cert.pfx
      - ASPNETCORE_IdentityServer__Key__FilePath=/certs/cert.pfx
      - ASPNETCORE_IdentityServer__Key__Password=${NETCORE_CERTIFICATE_PASSWORD}
      - ASPNETCORE_IdentityServer__Key__Type=File
      - ASPNETCORE_ConnectionStrings__DefaultConnection=User ID=${PG_USER};Password=${PG_PASSWORD};Server=ebay_postgres;Port=5432;Database=ebay;Pooling=true;MinPoolSize=1;MaxPoolSize=30;Enlist=true;
    networks:
      - ebay_internal_network

  ebay_odoo:
    container_name: ebay_odoo
    image: odoo:17.0
    depends_on:
      - ebay_postgres
    volumes:
      - ./config/odoo/config:/etc/odoo:ro
      - ./config/odoo/addons:/mnt/extra-addons:ro
      - odoo_data:/var/lib/odoo
    environment:
      - HOST=ebay_postgres
      - USER=${PG_USER}
      - PASSWORD=${PG_PASSWORD}
      - DATABASE=odoo
    networks:
      - ebay_internal_network
    restart: unless-stopped

  ebay_nginx:
    container_name: ebay_nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ${SSL_CERTIFICATE_DIR}:/certs/:ro
      - ./mount/nginx/logs/:/var/log/nginx/
    environment:
      - DOMAIN=${DOMAIN}
      - SSL_CERTIFICATE_FILE=/certs/${SSL_CERTIFICATE_FILE}
      - SSL_CERTIFICATE_KEY_FILE=/certs/${SSL_CERTIFICATE_KEY_FILE}
    networks:
      - ebay_internal_network
    restart: unless-stopped

networks:
  ebay_internal_network:
    driver: bridge

volumes:
  pgdata:
  odoo_data:
