name: ebay
services:
  ebay_postgres:
    container_name: ebay_postgres
    image: postgres:16.1
    ports:
      - "15432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ebay
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_INITDB_ARGS: --locale='en_US.UTF8'
      CFG_TIMEZONE: 'Europe/Moscow'
    volumes:
      - ./mount/postgres/data/:/var/lib/postgresql/data
    networks:
      - internal_network

  ebay_helper:
    container_name: ebay_helper
    image: ghcr.io/artyompetrov/ebay:latest
    depends_on:
      - ebay_postgres
    restart: unless-stopped
    volumes:
      - ${NETCORE_CERTIFICATE}:/certs/cert.pfx:ro
      - ebay_helper_keys:/app/DataProtection-Keys/
    environment:
      - DOMAIN=${DOMAIN}
      - ASPNETCORE_HTTP_PORTS="80"
      - ASPNETCORE_HTTPS_PORTS="443"
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${NETCORE_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/cert.pfx
      - ASPNETCORE_IdentityServer__Key__FilePath=/certs/cert.pfx
      - ASPNETCORE_IdentityServer__Key__Password=${NETCORE_CERTIFICATE_PASSWORD}
      - ASPNETCORE_IdentityServer__Key__Type=File
      - ASPNETCORE_ConnectionStrings__DefaultConnection=User ID=ebay;Password=${PG_PASSWORD};Server=ebay_postgres;Port=5432;Database=ebay;Pooling=true;MinPoolSize=1;MaxPoolSize=60;Enlist=true;
      - DATA_PROTECTION_KEYS_DIR=/app/DataProtection-Keys/
      - EbayServer__IsLocalRun=${LOCAL_RUN:-true}
      - EbayServer__TargetEmail=${EMAIL}
      - Smtp__Server=${SMTP_SERVER}
      - Smtp__Port=${SMTP_PORT}
      - Smtp__Login=${SMTP_LOGIN}
      - Smtp__Password=${SMTP_PASSWORD}
      - Smtp__Email=${EMAIL}
      - CLIENT_ID=${CLIENT_ID}
      - AUTH_SCOPE=${AUTH_SCOPE}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - RESTORE=${RESTORE:-false}
    networks:
      - internal_network
    entrypoint:
      - bash
      - -c
    command:
      - >
        if [ "${RESTORE:-false}" = "true" ]; then
          echo "Restoring backup...";
          while true; do sleep 86400; done;
        else
          dotnet Server.dll
        fi;

  ebay_nginx:
    container_name: ebay_nginx
    build: ./build/nginx
    ports:
      - "80:80"
      - "443:443"
      - "9443:9443"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./mount/nginx/logs/:/var/log/nginx/
      - ./mount/nginx/certs/:/etc/letsencrypt/
    environment:
      - DOMAIN=${DOMAIN}
      - SELF_SIGNED_CERTIFICATE=${LOCAL_RUN}
      - EMAIL=${EMAIL}
    networks:
      - internal_network
    restart: unless-stopped

  ebay_portainer:
    container_name: ebay_portainer
    image: portainer/portainer-ce
    restart: always
    command: >
      --admin-password '${PORTAINER_HASH}'
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal_network

  loki:
    container_name: loki
    image: grafana/loki:2.9.10
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/tmp/loki
    networks:
      - internal_network
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:10.4.2
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${PG_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - internal_network
    restart: unless-stopped

networks:
  internal_network:
    driver: bridge

volumes:
  redis_queue_data:
  ebay_helper_keys:
  portainer_data:
  loki_data:
  grafana_data:
