version: "3"

services:
  ebay_postgres:
    container_name: ebay_postgres
    image: postgres:16.1
    ports:
      - "15432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ebay
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_INITDB_ARGS: --locale='en_US.UTF8'
      CFG_TIMEZONE: 'Europe/Moscow'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ebay_internal_network

  ebay_helper:
    container_name: ebay_helper
    image: ghcr.io/artyompetrov/ebay:latest
    depends_on:
      - ebay_postgres
    restart: unless-stopped
    volumes:
      - ${NETCORE_CERTIFICATE}:/certs/cert.pfx:ro
    environment:
      - DOMAIN=${DOMAIN}
      - ASPNETCORE_URLS=https://+:443/
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${NETCORE_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certs/cert.pfx
      - ASPNETCORE_IdentityServer__Key__FilePath=/certs/cert.pfx
      - ASPNETCORE_IdentityServer__Key__Password=${NETCORE_CERTIFICATE_PASSWORD}
      - ASPNETCORE_IdentityServer__Key__Type=File
      - ASPNETCORE_ConnectionStrings__DefaultConnection=User ID=ebay;Password=${PG_PASSWORD};Server=ebay_postgres;Port=5432;Database=ebay;Pooling=true;MinPoolSize=1;MaxPoolSize=30;Enlist=true;
    networks:
      - ebay_internal_network

  ebay_nginx:
    container_name: ebay_nginx
    build: ./build/nginx
    ports:
      - "80:80"
      - "443:443"
      - "9443:9443"
    volumes:
      - ./mount/nginx/logs/:/var/log/nginx/
      - ./mount/nginx/certs/:/etc/letsencrypt/
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    networks:
      - ebay_internal_network
    restart: unless-stopped

  ebay_portainer:
    container_name: ebay_portainer
    image: portainer/portainer-ce
    restart: always
    command: >
      --admin-username ${PORTAINER_USER}
      --admin-password '${PORTAINER_HASH}'
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ebay_internal_network

networks:
  ebay_internal_network:
    driver: bridge

volumes:
  pgdata:
  portainer_data:
