#!/bin/bash
set -euo pipefail

# Uploads a local file to Yandex Disk via its REST API
# (https://yandex.ru/dev/disk/api/reference/).
#
# Usage: upload_to_yandex_disk.sh <local_file_path> <remote_disk_path>
#
# Requires the YANDEX_DISK_TOKEN environment variable (an OAuth token with
# Yandex Disk access, see https://yandex.ru/dev/disk/api/concepts/quickstart.html).
#
# This implicit-flow OAuth token (response_type=token) has no refresh token,
# so it cannot auto-renew: once it expires, YANDEX_DISK_TOKEN must be
# regenerated by hand via the re-authorization link below.

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <local_file_path> <remote_disk_path>" >&2
  exit 1
fi

local_file="$1"
remote_path="$2"

if [ -z "${YANDEX_DISK_TOKEN:-}" ]; then
  echo "YANDEX_DISK_TOKEN environment variable is required" >&2
  exit 1
fi

if [ ! -s "$local_file" ]; then
  echo "Local file not found or empty: $local_file" >&2
  exit 1
fi

# client_id of the Yandex OAuth app used to issue YANDEX_DISK_TOKEN.
# Override with YANDEX_OAUTH_CLIENT_ID if that app is ever replaced.
yandex_oauth_client_id="${YANDEX_OAUTH_CLIENT_ID}"

print_reauth_hint() {
  echo "Yandex Disk OAuth token appears to be expired or invalid (HTTP 401)." >&2
  echo "Re-authorize and put the new token into the YANDEX_DISK_TOKEN secret:" >&2
  echo "https://oauth.yandex.ru/authorize?response_type=token&client_id=${yandex_oauth_client_id}" >&2
}

api_base="https://cloud-api.yandex.net/v1/disk/resources"
auth_header="Authorization: OAuth ${YANDEX_DISK_TOKEN}"

create_folder() {
  local folder_path="$1"
  local http_code
  http_code=$(curl -sS -o /dev/null -w '%{http_code}' -X PUT \
    -H "$auth_header" \
    -G "$api_base" --data-urlencode "path=${folder_path}")
  # 201 - created, 409 - already exists, both are fine.
  if [ "$http_code" = "401" ]; then
    print_reauth_hint
    exit 1
  fi
  if [ "$http_code" != "201" ] && [ "$http_code" != "409" ]; then
    echo "Failed to create Yandex Disk folder '$folder_path' (HTTP $http_code)" >&2
    exit 1
  fi
}

# Yandex Disk requires every ancestor folder to exist before uploading into it.
remote_dir="${remote_path%/*}"
path_so_far=""
IFS='/' read -ra parts <<< "$remote_dir"
for part in "${parts[@]}"; do
  [ -z "$part" ] && continue
  path_so_far="${path_so_far}/${part}"
  create_folder "$path_so_far"
done

echo "Requesting Yandex Disk upload URL for ${remote_path}..."
upload_response=$(curl -sS -G "${api_base}/upload" \
  -H "$auth_header" \
  --data-urlencode "path=${remote_path}" \
  --data-urlencode "overwrite=true" \
  -w '\n%{http_code}')
upload_response_code="${upload_response##*$'\n'}"
upload_response_body="${upload_response%$'\n'*}"

if [ "$upload_response_code" = "401" ]; then
  print_reauth_hint
  exit 1
fi

upload_href=$(echo "$upload_response_body" | jq -r '.href')

if [ -z "$upload_href" ] || [ "$upload_href" = "null" ]; then
  echo "Failed to obtain Yandex Disk upload URL for ${remote_path} (HTTP $upload_response_code)" >&2
  exit 1
fi

echo "Uploading ${local_file} to disk:${remote_path}..."
http_code=$(curl -sS -o /dev/null -w '%{http_code}' -X PUT --upload-file "$local_file" "$upload_href")

if [ "$http_code" != "201" ] && [ "$http_code" != "202" ]; then
  echo "Upload to Yandex Disk failed (HTTP $http_code)" >&2
  exit 1
fi

echo "Backup uploaded successfully to disk:${remote_path}"
