openapi: 3.1.0
info:
  title: Ebay WebApi Adapter Contract
  version: 1.0.0
paths:
  /api/webapi/v1/lot-for-sales:
    get:
      operationId: GetLotForSales
      summary: Returns lot-for-sale aggregates
      tags:
        - WebApi
      responses:
        '200':
          description: List of lot-for-sale aggregates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LotForSaleResponse'
    post:
      operationId: CreateLotForSale
      summary: Creates lot-for-sale aggregate
      tags:
        - WebApi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LotForSaleCreateRequest'
      responses:
        '200':
          description: Ok
components:
  schemas:
    LotForSaleCreateRequest:
      type: object
      additionalProperties: false
      required:
        - id
        - name
        - productId
      properties:
        id:
          type: string
          minLength: 7
          maxLength: 7
        name:
          type: string
        productId:
          type: string
          format: uuid
    LotForSaleResponse:
      type: object
      additionalProperties: false
      required:
        - id
        - name
        - productId
      properties:
        id:
          type: string
          minLength: 7
          maxLength: 7
        name:
          type: string
        productId:
          type: string
          format: uuid
