using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Server.Adapters.Driven.EF.Identity.Migrations.Migrations
{
    /// <inheritdoc />
    public partial class InitialIdentity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Written as raw, "IF NOT EXISTS" SQL instead of the scaffolded fluent CreateTable/CreateIndex calls
            // so this migration is a no-op on a database that already has these tables from the legacy
            // ApplicationDbContext-owned migrations (schema verified byte-for-byte identical - see design.md's
            // Identity cutover risk framing) while still creating everything correctly on a genuinely fresh
            // database. Foreign keys are declared inline inside their owning CREATE TABLE, so no separate
            // guard is needed for them: they're skipped along with the rest of the table when it already exists.
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "AspNetRoles" (
                    "Id" text NOT NULL,
                    "Name" character varying(256),
                    "NormalizedName" character varying(256),
                    "ConcurrencyStamp" text,
                    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "AspNetUsers" (
                    "Id" text NOT NULL,
                    "UserName" character varying(256),
                    "NormalizedUserName" character varying(256),
                    "Email" character varying(256),
                    "NormalizedEmail" character varying(256),
                    "EmailConfirmed" boolean NOT NULL,
                    "PasswordHash" text,
                    "SecurityStamp" text,
                    "ConcurrencyStamp" text,
                    "PhoneNumber" text,
                    "PhoneNumberConfirmed" boolean NOT NULL,
                    "TwoFactorEnabled" boolean NOT NULL,
                    "LockoutEnd" timestamp with time zone,
                    "LockoutEnabled" boolean NOT NULL,
                    "AccessFailedCount" integer NOT NULL,
                    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "DeviceCodes" (
                    "UserCode" character varying(200) NOT NULL,
                    "DeviceCode" character varying(200) NOT NULL,
                    "SubjectId" character varying(200),
                    "SessionId" character varying(100),
                    "ClientId" character varying(200) NOT NULL,
                    "Description" character varying(200),
                    "CreationTime" timestamp with time zone NOT NULL,
                    "Expiration" timestamp with time zone NOT NULL,
                    "Data" character varying(50000) NOT NULL,
                    CONSTRAINT "PK_DeviceCodes" PRIMARY KEY ("UserCode")
                );

                CREATE TABLE IF NOT EXISTS "Keys" (
                    "Id" text NOT NULL,
                    "Version" integer NOT NULL,
                    "Created" timestamp with time zone NOT NULL,
                    "Use" text,
                    "Algorithm" character varying(100) NOT NULL,
                    "IsX509Certificate" boolean NOT NULL,
                    "DataProtected" boolean NOT NULL,
                    "Data" text NOT NULL,
                    CONSTRAINT "PK_Keys" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "PersistedGrants" (
                    "Key" character varying(200) NOT NULL,
                    "Type" character varying(50) NOT NULL,
                    "SubjectId" character varying(200),
                    "SessionId" character varying(100),
                    "ClientId" character varying(200) NOT NULL,
                    "Description" character varying(200),
                    "CreationTime" timestamp with time zone NOT NULL,
                    "Expiration" timestamp with time zone,
                    "ConsumedTime" timestamp with time zone,
                    "Data" character varying(50000) NOT NULL,
                    CONSTRAINT "PK_PersistedGrants" PRIMARY KEY ("Key")
                );

                CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "RoleId" text NOT NULL,
                    "ClaimType" text,
                    "ClaimValue" text,
                    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId" text NOT NULL,
                    "ClaimType" text,
                    "ClaimValue" text,
                    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
                    "LoginProvider" character varying(128) NOT NULL,
                    "ProviderKey" character varying(128) NOT NULL,
                    "ProviderDisplayName" text,
                    "UserId" text NOT NULL,
                    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
                    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
                    "UserId" text NOT NULL,
                    "RoleId" text NOT NULL,
                    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
                    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
                    "UserId" text NOT NULL,
                    "LoginProvider" character varying(128) NOT NULL,
                    "Name" character varying(128) NOT NULL,
                    "Value" text,
                    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
                    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
                CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
                CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
                CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
                CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
                CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
                CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_DeviceCodes_DeviceCode" ON "DeviceCodes" ("DeviceCode");
                CREATE INDEX IF NOT EXISTS "IX_DeviceCodes_Expiration" ON "DeviceCodes" ("Expiration");
                CREATE INDEX IF NOT EXISTS "IX_Keys_Use" ON "Keys" ("Use");
                CREATE INDEX IF NOT EXISTS "IX_PersistedGrants_ConsumedTime" ON "PersistedGrants" ("ConsumedTime");
                CREATE INDEX IF NOT EXISTS "IX_PersistedGrants_Expiration" ON "PersistedGrants" ("Expiration");
                CREATE INDEX IF NOT EXISTS "IX_PersistedGrants_SubjectId_ClientId_Type" ON "PersistedGrants" ("SubjectId", "ClientId", "Type");
                CREATE INDEX IF NOT EXISTS "IX_PersistedGrants_SubjectId_SessionId_Type" ON "PersistedGrants" ("SubjectId", "SessionId", "Type");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AspNetRoleClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserClaims");

            migrationBuilder.DropTable(
                name: "AspNetUserLogins");

            migrationBuilder.DropTable(
                name: "AspNetUserRoles");

            migrationBuilder.DropTable(
                name: "AspNetUserTokens");

            migrationBuilder.DropTable(
                name: "DeviceCodes");

            migrationBuilder.DropTable(
                name: "Keys");

            migrationBuilder.DropTable(
                name: "PersistedGrants");

            migrationBuilder.DropTable(
                name: "AspNetRoles");

            migrationBuilder.DropTable(
                name: "AspNetUsers");
        }
    }
}
