<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <WarningsNotAsErrors>CS0612,CS0618,CS1591</WarningsNotAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="ErrorProne.NET.CoreAnalyzers">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    
</Project>
