<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Server.Application.New\Server.Application.New.fsproj" />
      <ProjectReference Include="..\Server.Application\Server.Application.csproj" />
    </ItemGroup>

</Project>
