# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.lot_info_short import LotInfoShort

class TestLotInfoShort(unittest.TestCase):
    """LotInfoShort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LotInfoShort:
        """Test LotInfoShort
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LotInfoShort`
        """
        model = LotInfoShort()
        if include_optional:
            return LotInfoShort(
                lot_id = 56,
                name = '0',
                pcs = 1,
                shipping_country = '0',
                currency = '0',
                price = 0.01,
                shipping = 0,
                shipping_additional = 0,
                condition = '0',
                condition_description = '0',
                seller = '0',
                located_in = '0',
                manual_condition_id = 'E0',
                purchase_history = [
                    openapi_client.models.purchase_info.PurchaseInfo(
                        price = 0.01, 
                        quantity = 1, 
                        date = '0480-72-88T80:01:52.802Z0', )
                    ]
            )
        else:
            return LotInfoShort(
                lot_id = 56,
                name = '0',
                pcs = 1,
                shipping_country = '0',
                currency = '0',
                price = 0.01,
                condition = '0',
                seller = '0',
                located_in = '0',
                manual_condition_id = 'E0',
                purchase_history = [
                    openapi_client.models.purchase_info.PurchaseInfo(
                        price = 0.01, 
                        quantity = 1, 
                        date = '0480-72-88T80:01:52.802Z0', )
                    ],
        )
        """

    def testLotInfoShort(self):
        """Test LotInfoShort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
