<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Server.Contracts</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Legacy/**/*.yaml" />
    <None Include="WebApi/**/*.yaml" />
  </ItemGroup>

</Project>
