# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.manual_condition import ManualCondition  # noqa: E501

class TestManualCondition(unittest.TestCase):
    """ManualCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManualCondition:
        """Test ManualCondition
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManualCondition`
        """
        model = ManualCondition()  # noqa: E501
        if include_optional:
            return ManualCondition(
                id = '',
                description = ''
            )
        else:
            return ManualCondition(
                id = '',
                description = '',
        )
        """

    def testManualCondition(self):
        """Test ManualCondition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
