# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.lot_data_to_extract import LotDataToExtract  # noqa: E501

class TestLotDataToExtract(unittest.TestCase):
    """LotDataToExtract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LotDataToExtract:
        """Test LotDataToExtract
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LotDataToExtract`
        """
        model = LotDataToExtract()  # noqa: E501
        if include_optional:
            return LotDataToExtract(
                name = '0',
                condition = '0',
                condition_description = '0',
                description = '0',
                short_description = '0',
                lot_size = 56
            )
        else:
            return LotDataToExtract(
                name = '0',
                condition = '0',
                description = '0',
        )
        """

    def testLotDataToExtract(self):
        """Test LotDataToExtract"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
