# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.shipping_type import ShippingType  # noqa: E501

class TestShippingType(unittest.TestCase):
    """ShippingType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShippingType:
        """Test ShippingType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShippingType`
        """
        model = ShippingType()  # noqa: E501
        if include_optional:
            return ShippingType(
                name = '0',
                currency = '0',
                rates = [
                    openapi_client.models.shipping_rates.ShippingRates(
                        specified_countries = [
                            '0'
                            ], 
                        rates = [
                            openapi_client.models.shipping_rate.ShippingRate(
                                min_weight = 0, 
                                max_weight = 0, 
                                price = 0, )
                            ], )
                    ]
            )
        else:
            return ShippingType(
                name = '0',
                currency = '0',
                rates = [
                    openapi_client.models.shipping_rates.ShippingRates(
                        specified_countries = [
                            '0'
                            ], 
                        rates = [
                            openapi_client.models.shipping_rate.ShippingRate(
                                min_weight = 0, 
                                max_weight = 0, 
                                price = 0, )
                            ], )
                    ],
        )
        """

    def testShippingType(self):
        """Test ShippingType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
