# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.lot_state import LotState  # noqa: E501

class TestLotState(unittest.TestCase):
    """LotState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LotState:
        """Test LotState
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LotState`
        """
        model = LotState()  # noqa: E501
        if include_optional:
            return LotState(
                lot_id = 56,
                ignore_that_lot = True,
                last_update = '0480-72-88T80:01:52.802Z'
            )
        else:
            return LotState(
                lot_id = 56,
                ignore_that_lot = True,
                last_update = '0480-72-88T80:01:52.802Z',
        )
        """

    def testLotState(self):
        """Test LotState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
