# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.validation_problem_detailed_info import ValidationProblemDetailedInfo  # noqa: E501

class TestValidationProblemDetailedInfo(unittest.TestCase):
    """ValidationProblemDetailedInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationProblemDetailedInfo:
        """Test ValidationProblemDetailedInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationProblemDetailedInfo`
        """
        model = ValidationProblemDetailedInfo()  # noqa: E501
        if include_optional:
            return ValidationProblemDetailedInfo(
                errors = None,
                type = '',
                title = '',
                status = 56,
                detail = '',
                instance = ''
            )
        else:
            return ValidationProblemDetailedInfo(
        )
        """

    def testValidationProblemDetailedInfo(self):
        """Test ValidationProblemDetailedInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
