# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_product(self) -> None:
        """Test case for create_product

        Create product  # noqa: E501
        """
        pass

    def test_delete_product(self) -> None:
        """Test case for delete_product

        Delete product  # noqa: E501
        """
        pass

    def test_get_all_products(self) -> None:
        """Test case for get_all_products

        List all products  # noqa: E501
        """
        pass

    def test_get_currencies(self) -> None:
        """Test case for get_currencies

        """
        pass

    def test_get_lot_info(self) -> None:
        """Test case for get_lot_info

        Получить информацию о лоте  # noqa: E501
        """
        pass

    def test_get_lot_states(self) -> None:
        """Test case for get_lot_states

        Получает информацию о учтенных лотах  # noqa: E501
        """
        pass

    def test_get_lots(self) -> None:
        """Test case for get_lots

        """
        pass

    def test_get_manual_conditions_list(self) -> None:
        """Test case for get_manual_conditions_list

        Отдает перечень возможных состояний продаваемого товара  # noqa: E501
        """
        pass

    def test_get_product(self) -> None:
        """Test case for get_product

        """
        pass

    def test_get_shipping_rates(self) -> None:
        """Test case for get_shipping_rates

        """
        pass

    def test_mark_product_as_checked(self) -> None:
        """Test case for mark_product_as_checked

        MarkProductAsChecked  # noqa: E501
        """
        pass

    def test_save_error(self) -> None:
        """Test case for save_error

        Save Error  # noqa: E501
        """
        pass

    def test_update_product(self) -> None:
        """Test case for update_product

        Update product  # noqa: E501
        """
        pass

    def test_upsert_lot_info(self) -> None:
        """Test case for upsert_lot_info

        Обновляет информацию о лоте  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
