# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.category_item import CategoryItem  # noqa: E501

class TestCategoryItem(unittest.TestCase):
    """CategoryItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CategoryItem:
        """Test CategoryItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CategoryItem`
        """
        model = CategoryItem()  # noqa: E501
        if include_optional:
            return CategoryItem(
                id = '_0',
                description = '_0'
            )
        else:
            return CategoryItem(
                id = '_0',
                description = '_0',
        )
        """

    def testCategoryItem(self):
        """Test CategoryItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
