# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.extractor_info import ExtractorInfo  # noqa: E501

class TestExtractorInfo(unittest.TestCase):
    """ExtractorInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtractorInfo:
        """Test ExtractorInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtractorInfo`
        """
        model = ExtractorInfo()  # noqa: E501
        if include_optional:
            return ExtractorInfo(
                extracted_from = '0',
                extractor = '0',
                match = '0'
            )
        else:
            return ExtractorInfo(
                extracted_from = '0',
                extractor = '0',
                match = '0',
        )
        """

    def testExtractorInfo(self):
        """Test ExtractorInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
