# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.lot_info_with_product_id import LotInfoWithProductId  # noqa: E501

class TestLotInfoWithProductId(unittest.TestCase):
    """LotInfoWithProductId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LotInfoWithProductId:
        """Test LotInfoWithProductId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LotInfoWithProductId`
        """
        model = LotInfoWithProductId()  # noqa: E501
        if include_optional:
            return LotInfoWithProductId(
                product_id = '',
                lot_info = openapi_client.models.lot_info.LotInfo(
                    lot_id = 56, 
                    name = '0', 
                    pcs = 1, 
                    shipping_country = '0', 
                    currency = '0', 
                    price = 0.01, 
                    shipping = 0, 
                    shipping_additional = 0, 
                    description = '0', 
                    condition = '0', 
                    condition_description = '0', 
                    seller = '0', 
                    located_in = '0', 
                    ignore_that_lot = True, 
                    categories = [
                        openapi_client.models.category_value.CategoryValue(
                            type = '_0', 
                            value = '_0', )
                        ], 
                    title_change_date = '0480-72-88T80:01:52.802Z0', 
                    purchase_history = [
                        openapi_client.models.purchase_info.PurchaseInfo(
                            price = 0.01, 
                            quantity = 1, 
                            date = '0480-72-88T80:01:52.802Z0', )
                        ], )
            )
        else:
            return LotInfoWithProductId(
                product_id = '',
                lot_info = openapi_client.models.lot_info.LotInfo(
                    lot_id = 56, 
                    name = '0', 
                    pcs = 1, 
                    shipping_country = '0', 
                    currency = '0', 
                    price = 0.01, 
                    shipping = 0, 
                    shipping_additional = 0, 
                    description = '0', 
                    condition = '0', 
                    condition_description = '0', 
                    seller = '0', 
                    located_in = '0', 
                    ignore_that_lot = True, 
                    categories = [
                        openapi_client.models.category_value.CategoryValue(
                            type = '_0', 
                            value = '_0', )
                        ], 
                    title_change_date = '0480-72-88T80:01:52.802Z0', 
                    purchase_history = [
                        openapi_client.models.purchase_info.PurchaseInfo(
                            price = 0.01, 
                            quantity = 1, 
                            date = '0480-72-88T80:01:52.802Z0', )
                        ], ),
        )
        """

    def testLotInfoWithProductId(self):
        """Test LotInfoWithProductId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
