# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictInt, field_validator
from pydantic import Field
from typing_extensions import Annotated
from openapi_client.models.purchase_info import PurchaseInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class LotInfo(BaseModel):
    """
    LotInfo
    """ # noqa: E501
    lot_id: StrictInt = Field(alias="lotId")
    name: Annotated[str, Field(min_length=1, strict=True)]
    pcs: Annotated[int, Field(strict=True, ge=1)]
    shipping_country: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="shippingCountry")
    currency: Annotated[str, Field(min_length=1, strict=True)]
    price: Union[Annotated[float, Field(strict=True, ge=0.01)], Annotated[int, Field(strict=True, ge=1)]]
    shipping: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    shipping_additional: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, alias="shippingAdditional")
    description: Annotated[str, Field(min_length=1, strict=True)]
    condition: Annotated[str, Field(min_length=1, strict=True)]
    condition_description: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="conditionDescription")
    seller: Annotated[str, Field(min_length=1, strict=True)]
    located_in: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="locatedIn")
    ignore_that_lot: StrictBool = Field(alias="ignoreThatLot")
    manual_condition_id: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="manualConditionId")
    purchase_history: List[PurchaseInfo] = Field(alias="purchaseHistory")
    __properties: ClassVar[List[str]] = ["lotId", "name", "pcs", "shippingCountry", "currency", "price", "shipping", "shippingAdditional", "description", "condition", "conditionDescription", "seller", "locatedIn", "ignoreThatLot", "manualConditionId", "purchaseHistory"]

    @field_validator('manual_condition_id')
    def manual_condition_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Za-z]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z]+$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LotInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in purchase_history (list)
        _items = []
        if self.purchase_history:
            for _item in self.purchase_history:
                if _item:
                    _items.append(_item.to_dict())
            _dict['purchaseHistory'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LotInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lotId": obj.get("lotId"),
            "name": obj.get("name"),
            "pcs": obj.get("pcs"),
            "shippingCountry": obj.get("shippingCountry"),
            "currency": obj.get("currency"),
            "price": obj.get("price"),
            "shipping": obj.get("shipping"),
            "shippingAdditional": obj.get("shippingAdditional"),
            "description": obj.get("description"),
            "condition": obj.get("condition"),
            "conditionDescription": obj.get("conditionDescription"),
            "seller": obj.get("seller"),
            "locatedIn": obj.get("locatedIn"),
            "ignoreThatLot": obj.get("ignoreThatLot"),
            "manualConditionId": obj.get("manualConditionId"),
            "purchaseHistory": [PurchaseInfo.from_dict(_item) for _item in obj.get("purchaseHistory")] if obj.get("purchaseHistory") is not None else None
        })
        return _obj


