<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="NSwag.MSBuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <Target Name="GenerateClients" BeforeTargets="CoreCompile">
        <Exec Command="$(NSwagExe_Net100) run ClientGeneration.Legacy.json" />
        <Exec Command="$(NSwagExe_Net100) run ClientGeneration.WebApi.json" />
    </Target>

    <Target Name="IncludeGeneratedClients" BeforeTargets="CoreCompile" DependsOnTargets="GenerateClients">
        <ItemGroup>
            <Compile Include="$(BaseIntermediateOutputPath)Generated/Clients/**/*.cs" />
        </ItemGroup>
    </Target>

</Project>
