<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json"/>
        <PackageReference Include="NSwag.MSBuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Generated\" />
    </ItemGroup>

    <Target Name="NSwag" BeforeTargets="BeforeBuild">
        <Exec Command="$(NSwagExe_Net100) openapi2csclient /input:../Server.Contracts/Legacy/Ebay.yaml /classname:EbayClient /namespace:Client.Clients.Generated /output:./Generated/EbayClient.cs /RequiredPropertiesMustBeDefined:false"/>
    </Target>
</Project>
