<Project Sdk="Microsoft.NET.Sdk.Razor">
   <ItemGroup>
        <PackageReference Include="alglib.net" />
        <PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" />
        <PackageReference Include="HtmlAgilityPack" />
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="MassTransit" />
        <PackageReference Include="MassTransit.EntityFrameworkCore" />
        <PackageReference Include="MassTransit.SqlTransport.PostgreSQL" />
        <PackageReference Include="Npgsql.DependencyInjection" />
        <PackageReference Include="OpenExchangeRates.NET" />
        <PackageReference Include="ScottPlot" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
        <PackageReference Include="Microsoft.AspNetCore.ApiAuthorization.IdentityServer" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Server.Domain\Server.Domain.csproj" />
    </ItemGroup>

</Project>
