<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <RootNamespace>Server.Adapters.WebApi</RootNamespace>
    <RazorCompileOnBuild>true</RazorCompileOnBuild>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.ApiAuthorization.IdentityServer" />
    <PackageReference Include="NSwag.MSBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Server.Application.New\Server.Application.New.csproj" />
    <ProjectReference Include="..\Server.Domain\Server.Domain.csproj" />
  </ItemGroup>

  <Target Name="GenerateControllers" BeforeTargets="CoreCompile">
    <Exec Command="$(NSwagExe_Net100) run ControllerGenerationConfig.json" />
  </Target>

  <Target Name="IncludeGeneratedControllers" BeforeTargets="CoreCompile" DependsOnTargets="GenerateControllers">
    <ItemGroup>
      <Compile Include="$(BaseIntermediateOutputPath)Generated/Controllers/**/*.cs" />
    </ItemGroup>
  </Target>

</Project>
