<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
        <WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" />
    </ItemGroup>

</Project>
