# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, constr, validator

class CategoryValue(BaseModel):
    """
    CategoryValue
    """
    type: constr(strict=True, min_length=1) = Field(...)
    value: constr(strict=True, min_length=1) = Field(...)
    __properties = ["type", "value"]

    @validator('type')
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Za-z_]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z_]+$/")
        return value

    @validator('value')
    def value_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Za-z_]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z_]+$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CategoryValue:
        """Create an instance of CategoryValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CategoryValue:
        """Create an instance of CategoryValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CategoryValue.parse_obj(obj)

        _obj = CategoryValue.parse_obj({
            "type": obj.get("type"),
            "value": obj.get("value")
        })
        return _obj


