# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist, constr
from openapi_client.models.lot_data_extracted_item import LotDataExtractedItem

class ExtractedFields(BaseModel):
    """
    ExtractedFields
    """
    field_name: constr(strict=True, min_length=1) = Field(..., alias="fieldName")
    extracted_data: conlist(LotDataExtractedItem) = Field(..., alias="extractedData")
    __properties = ["fieldName", "extractedData"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExtractedFields:
        """Create an instance of ExtractedFields from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in extracted_data (list)
        _items = []
        if self.extracted_data:
            for _item in self.extracted_data:
                if _item:
                    _items.append(_item.to_dict())
            _dict['extractedData'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExtractedFields:
        """Create an instance of ExtractedFields from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ExtractedFields.parse_obj(obj)

        _obj = ExtractedFields.parse_obj({
            "field_name": obj.get("fieldName"),
            "extracted_data": [LotDataExtractedItem.from_dict(_item) for _item in obj.get("extractedData")] if obj.get("extractedData") is not None else None
        })
        return _obj


