# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, Field, confloat, conint, constr, validator

class PurchaseInfo(BaseModel):
    """
    PurchaseInfo
    """
    price: Optional[Union[confloat(ge=0.01, strict=True), conint(ge=1, strict=True)]] = None
    quantity: conint(strict=True, ge=1) = Field(...)
    var_date: constr(strict=True, min_length=1) = Field(..., alias="date")
    __properties = ["price", "quantity", "date"]

    @validator('var_date')
    def var_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$", value):
            raise ValueError(r"must validate the regular expression /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PurchaseInfo:
        """Create an instance of PurchaseInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PurchaseInfo:
        """Create an instance of PurchaseInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PurchaseInfo.parse_obj(obj)

        _obj = PurchaseInfo.parse_obj({
            "price": obj.get("price"),
            "quantity": obj.get("quantity"),
            "var_date": obj.get("date")
        })
        return _obj


