# coding: utf-8

"""
    EbayApi

    EbayApi

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist, constr
from openapi_client.models.shipping_rates import ShippingRates

class ShippingType(BaseModel):
    """
    ShippingType
    """
    name: constr(strict=True, min_length=1) = Field(...)
    currency: constr(strict=True, min_length=1) = Field(...)
    rates: conlist(ShippingRates) = Field(...)
    __properties = ["name", "currency", "rates"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ShippingType:
        """Create an instance of ShippingType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in rates (list)
        _items = []
        if self.rates:
            for _item in self.rates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['rates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ShippingType:
        """Create an instance of ShippingType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ShippingType.parse_obj(obj)

        _obj = ShippingType.parse_obj({
            "name": obj.get("name"),
            "currency": obj.get("currency"),
            "rates": [ShippingRates.from_dict(_item) for _item in obj.get("rates")] if obj.get("rates") is not None else None
        })
        return _obj


