/*
 * EbayApi
 *
 * EbayApi
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Ebay.GeneratedController.Attributes;
using Ebay.GeneratedController.Models;

namespace Ebay.GeneratedController.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// List API versions
        /// </summary>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/api/ebay/v1/")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(List<WeatherForecast>))]
        public abstract Task<IActionResult> GetAll();
    }
}
