<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>Server-9A4AB6A1-13E5-44E4-8252-FA741476F495</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>Server</RootNamespace>
    </PropertyGroup>

  <ItemGroup>
      <ProjectReference Include="..\Server.Adapters.Driven.ChipFind\Server.Adapters.Driven.ChipFind.csproj" />
      <ProjectReference Include="..\Server.Adapters.Driven.EF.ReadModel\Server.Adapters.Driven.EF.ReadModel.csproj" />
      <ProjectReference Include="..\Server.Adapters.Driven.EF.WriteModel\Server.Adapters.Driven.EF.WriteModel.csproj" />
      <ProjectReference Include="..\Server.Adapters.Driven.EF.WriteModel.Migrations\Server.Adapters.Driven.EF.WriteModel.Migrations.csproj" />
      <ProjectReference Include="..\Server.Adapters.Driven.Smtp\Server.Adapters.Driven.Smtp.csproj" />
      <ProjectReference Include="..\Server.Adapters.Driven.uTracer\Server.Adapters.Driven.uTracer.csproj" />
      <ProjectReference Include="..\Server.Adapters.Driving.MassTransit\Server.Adapters.Driving.MassTransit.csproj" />
      <ProjectReference Include="..\Server.Adapters.Driving.BackgroundTasks\Server.Adapters.Driving.BackgroundTasks.csproj" />
      <ProjectReference Include="..\Server.Adapters.Driving.OpenExchangeRates\Server.Adapters.Driving.OpenExchangeRates.csproj" />
      <ProjectReference Include="..\Server.Application\Server.Application.csproj" />
      <ProjectReference Include="..\Server.Adapters.Driving.WebApi\Server.Adapters.Driving.WebApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <Content Update="appsettings.Development.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
