<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>Server-9A4AB6A1-13E5-44E4-8252-FA741476F495</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>Server</RootNamespace>
    </PropertyGroup>

  <ItemGroup>
      <ProjectReference Include="..\Server.Adapters.ChipFind\Server.Adapters.ChipFind.csproj" />
      <ProjectReference Include="..\Server.Adapters.Smtp\Server.Adapters.Smtp.csproj" />
      <ProjectReference Include="..\Server.Application\Server.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Npgsql" />
  </ItemGroup>


</Project>
