<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>Server-9A4AB6A1-13E5-44E4-8252-FA741476F495</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>Server</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" />
        <PackageReference Include="HtmlAgilityPack" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson"/>
        <PackageReference Include="Npgsql.DependencyInjection" />
        <PackageReference Include="NSwag.MSBuild">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="OpenExchangeRates.NET" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Client\Client.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI"/>
        <PackageReference Include="Microsoft.AspNetCore.ApiAuthorization.IdentityServer"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Data\Migrations\"/>
    </ItemGroup>

    <Target Name="NSwag" BeforeTargets="Build">
        <Exec Command="$(NSwagExe_Net80) openapi2cscontroller /input:Controllers/Contracts/Ebay.yaml /classname:Ebay /namespace:Server.Controllers.Generated /output:Controllers/Generated/EbayController.cs /ControllerBaseClass:Microsoft.AspNetCore.Mvc.Controller /UseCancellationToken:true /GenerateImmutableArrayProperties:true /GenerateImmutableDictionaryProperties:true /GenerateNullableReferenceTypes:true /GenerateOptionalPropertiesAsNullable:true /ClassStyle:Record /ExcludedTypeNames:ProblemDetails,ValidationProblemDetails /RequiredPropertiesMustBeDefined:false"/>
        <Exec Command="$(NSwagExe_Net80) openapi2tsclient /input:Controllers/Contracts/Ebay.yaml /output:../../ChromeExtension/EbayClient/EbayToolBackendClient.ts /ClassName:EbayToolBackendClient"/>
    </Target>

</Project>
