name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'      # Запускается на все ветки

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  EBAY_HELPER_IMAGE_NAME: ${{ github.actor }}/ebay:latest

jobs:
  build_docker:
    name: Build Ebay Helper Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          BUILD_VERSION=$(date +'%y%m.%d.%H.%M%S' | sed 's/\.0*/./g')
          docker build -f ./src/ebay_helper.Dockerfile --build-arg BUILD_VERSION="$BUILD_VERSION" --build-arg EBAY_HELPER_BACKEND_DOMAIN="${{ secrets.EBAY_HELPER_BACKEND_DOMAIN }}" --build-arg EBAY_CLIENT_ID="${{ secrets.EBAY_CLIENT_ID }}" --build-arg EBAY_CLIENT_SECRET="${{ secrets.EBAY_CLIENT_SECRET }}" --build-arg EBAY_REDIRECT_URI_CODE="${{ secrets.EBAY_REDIRECT_URI_CODE }}" --tag ${{ env.REGISTRY }}/${{ env.EBAY_HELPER_IMAGE_NAME }} ./src/
          docker save ${{ env.REGISTRY }}/${{ env.EBAY_HELPER_IMAGE_NAME }} -o image.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-image
          path: image.tar
          retention-days: 5

  publish_docker:
    name: Push Ebay Helper Docker Image
    runs-on: ubuntu-latest
    needs: build_docker
    if: github.ref == 'refs/heads/main'  # Запускается только на ветке main

    steps:
      - uses: actions/checkout@v3

      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-image
          path: .
      - name: Load Docker Image
        run: docker load -i image.tar

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PAT }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image
        run: docker push ${{ env.REGISTRY }}/${{ env.EBAY_HELPER_IMAGE_NAME }}

  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    needs: [ publish_docker ]
    if: github.ref == 'refs/heads/main'  # Запускается только на ветке main

    steps:
      - name: Install SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect and Pull Latest Image
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && ./update.sh"

      - name: Cleanup SSH
        run: rm -rf ~/.ssh

