#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
EXPECTED_VERSION="$(cat "$ROOT_DIR/.openspec-version")"

if ! command -v openspec >/dev/null 2>&1; then
  echo "openspec CLI not found on PATH (expected version $EXPECTED_VERSION, see .openspec-version)." >&2
  exit 1
fi

INSTALLED_VERSION="$(openspec --version)"
if [ "$INSTALLED_VERSION" != "$EXPECTED_VERSION" ]; then
  echo "openspec CLI version mismatch: installed $INSTALLED_VERSION, expected $EXPECTED_VERSION (see .openspec-version)." >&2
  echo "Run: npm install -g @fission-ai/openspec@$EXPECTED_VERSION" >&2
  exit 1
fi

failed=0
shopt -s nullglob
for skill_file in "$ROOT_DIR"/.claude/skills/openspec-*/SKILL.md; do
  generated_by="$(grep -m1 -E '^[[:space:]]*generatedBy:' "$skill_file" | sed -E 's/^[[:space:]]*generatedBy:[[:space:]]*"?([^"[:space:]]+)"?[[:space:]]*$/\1/')"
  if [ "$generated_by" != "$EXPECTED_VERSION" ]; then
    echo "Skill out of date: $skill_file was generated by '${generated_by:-<none>}', expected $EXPECTED_VERSION." >&2
    failed=1
  fi
done

if [ "$failed" -ne 0 ]; then
  echo "Run 'openspec update' with openspec CLI $EXPECTED_VERSION installed and commit the regenerated skills." >&2
  exit 1
fi

echo "openspec CLI ($INSTALLED_VERSION) and skills are in sync."
